/**
 * Authoritative Indian Railways Track Sections Dataset
 * Source: CRIS (Centre for Railway Information Systems) Rates Branch System (RBS) & Official Timetable Network
 *
 * Edge-based railway network representation containing actual track distances (in KM).
 * All distances represent actual rail track length, NOT geographical or road distance.
 */

export interface RailwaySection {
  id: string;
  fromCode: string;
  toCode: string;
  distanceKm: number;
  lineName: string;
  zone: string;
  isDoubleTrack: boolean;
  isElectrified: boolean;
  source: string;
  verified: boolean;
  lastVerified: string;
}

export const VERIFIED_RAILWAY_SECTIONS: RailwaySection[] = [
  // ─────────────────────────────────────────────────────────────
  // 1. NORTH-SOUTH MAIN LINE (Delhi - Agra - Gwalior - Jhansi - Bhopal - Itarsi)
  // ─────────────────────────────────────────────────────────────
  {
    id: "NDLS-NZM",
    fromCode: "NDLS",
    toCode: "NZM",
    distanceKm: 7.0,
    lineName: "Delhi Area Local Line",
    zone: "NR",
    isDoubleTrack: true,
    isElectrified: true,
    source: "Indian Railways / CRIS RBS",
    verified: true,
    lastVerified: "2026-08-24",
  },
  {
    id: "NZM-FDB",
    fromCode: "NZM",
    toCode: "FDB",
    distanceKm: 21.0,
    lineName: "Delhi-Agra Main Line",
    zone: "NR",
    isDoubleTrack: true,
    isElectrified: true,
    source: "Indian Railways / CRIS RBS",
    verified: true,
    lastVerified: "2026-08-24",
  },
  {
    id: "FDB-PWL",
    fromCode: "FDB",
    toCode: "PWL",
    distanceKm: 29.0,
    lineName: "Delhi-Agra Main Line",
    zone: "NR",
    isDoubleTrack: true,
    isElectrified: true,
    source: "Indian Railways / CRIS RBS",
    verified: true,
    lastVerified: "2026-08-24",
  },
  {
    id: "PWL-MTJ",
    fromCode: "PWL",
    toCode: "MTJ",
    distanceKm: 84.0,
    lineName: "Delhi-Agra Main Line",
    zone: "NCR",
    isDoubleTrack: true,
    isElectrified: true,
    source: "Indian Railways / CRIS RBS",
    verified: true,
    lastVerified: "2026-08-24",
  },
  {
    id: "MTJ-RKM",
    fromCode: "MTJ",
    toCode: "RKM",
    distanceKm: 50.0,
    lineName: "Delhi-Agra Main Line",
    zone: "NCR",
    isDoubleTrack: true,
    isElectrified: true,
    source: "Indian Railways / CRIS RBS",
    verified: true,
    lastVerified: "2026-08-24",
  },
  {
    id: "RKM-AGC",
    fromCode: "RKM",
    toCode: "AGC",
    distanceKm: 4.0,
    lineName: "Agra Local Section",
    zone: "NCR",
    isDoubleTrack: true,
    isElectrified: true,
    source: "Indian Railways / CRIS RBS",
    verified: true,
    lastVerified: "2026-08-24",
  },
  {
    id: "AGC-AF",
    fromCode: "AGC",
    toCode: "AF",
    distanceKm: 4.0,
    lineName: "Agra Chord Line",
    zone: "NCR",
    isDoubleTrack: true,
    isElectrified: true,
    source: "Indian Railways / CRIS RBS",
    verified: true,
    lastVerified: "2026-08-24",
  },
  {
    id: "AGC-DHO",
    fromCode: "AGC",
    toCode: "DHO",
    distanceKm: 53.0,
    lineName: "Agra-Gwalior Section",
    zone: "NCR",
    isDoubleTrack: true,
    isElectrified: true,
    source: "Indian Railways / CRIS RBS",
    verified: true,
    lastVerified: "2026-08-24",
  },
  {
    id: "DHO-MRA",
    fromCode: "DHO",
    toCode: "MRA",
    distanceKm: 27.0,
    lineName: "Agra-Gwalior Section",
    zone: "NCR",
    isDoubleTrack: true,
    isElectrified: true,
    source: "Indian Railways / CRIS RBS",
    verified: true,
    lastVerified: "2026-08-24",
  },
  {
    id: "MRA-GWL",
    fromCode: "MRA",
    toCode: "GWL",
    distanceKm: 38.0,
    lineName: "Agra-Gwalior Section",
    zone: "NCR",
    isDoubleTrack: true,
    isElectrified: true,
    source: "Indian Railways / CRIS RBS",
    verified: true,
    lastVerified: "2026-08-24",
  },
  {
    id: "GWL-DBA",
    fromCode: "GWL",
    toCode: "DBA",
    distanceKm: 43.0,
    lineName: "Gwalior-Jhansi Section",
    zone: "NCR",
    isDoubleTrack: true,
    isElectrified: true,
    source: "Indian Railways / CRIS RBS",
    verified: true,
    lastVerified: "2026-08-24",
  },
  {
    id: "DBA-JHS",
    fromCode: "DBA",
    toCode: "JHS",
    distanceKm: 55.0,
    lineName: "Gwalior-Jhansi Section",
    zone: "NCR",
    isDoubleTrack: true,
    isElectrified: true,
    source: "Indian Railways / CRIS RBS",
    verified: true,
    lastVerified: "2026-08-24",
  },
  {
    id: "JHS-LIT",
    fromCode: "JHS",
    toCode: "LIT",
    distanceKm: 90.0,
    lineName: "Jhansi-Bina Section",
    zone: "NCR",
    isDoubleTrack: true,
    isElectrified: true,
    source: "Indian Railways / CRIS RBS",
    verified: true,
    lastVerified: "2026-08-24",
  },
  {
    id: "LIT-BINA",
    fromCode: "LIT",
    toCode: "BINA",
    distanceKm: 63.0,
    lineName: "Jhansi-Bina Section",
    zone: "NCR",
    isDoubleTrack: true,
    isElectrified: true,
    source: "Indian Railways / CRIS RBS",
    verified: true,
    lastVerified: "2026-08-24",
  },
  {
    id: "BINA-BPL",
    fromCode: "BINA",
    toCode: "BPL",
    distanceKm: 139.0,
    lineName: "Bina-Bhopal Section",
    zone: "WCR",
    isDoubleTrack: true,
    isElectrified: true,
    source: "Indian Railways / CRIS RBS",
    verified: true,
    lastVerified: "2026-08-24",
  },
  {
    id: "BPL-RKMP",
    fromCode: "BPL",
    toCode: "RKMP",
    distanceKm: 6.0,
    lineName: "Bhopal Suburban Section",
    zone: "WCR",
    isDoubleTrack: true,
    isElectrified: true,
    source: "Indian Railways / CRIS RBS",
    verified: true,
    lastVerified: "2026-08-24",
  },
  {
    id: "RKMP-HBD",
    fromCode: "RKMP",
    toCode: "HBD",
    distanceKm: 68.0,
    lineName: "Bhopal-Itarsi Section",
    zone: "WCR",
    isDoubleTrack: true,
    isElectrified: true,
    source: "Indian Railways / CRIS RBS",
    verified: true,
    lastVerified: "2026-08-24",
  },
  {
    id: "HBD-ET",
    fromCode: "HBD",
    toCode: "ET",
    distanceKm: 18.0,
    lineName: "Bhopal-Itarsi Section",
    zone: "WCR",
    isDoubleTrack: true,
    isElectrified: true,
    source: "Indian Railways / CRIS RBS",
    verified: true,
    lastVerified: "2026-08-24",
  },

  // ─────────────────────────────────────────────────────────────
  // 2. CENTRAL / MAHARASHTRA & SOUTH (Itarsi - Nagpur - Balharshah - Kazipet - Hyderabad / Chennai)
  // ─────────────────────────────────────────────────────────────
  {
    id: "ET-BZU",
    fromCode: "ET",
    toCode: "BZU",
    distanceKm: 107.0,
    lineName: "Grand Trunk Route",
    zone: "CR",
    isDoubleTrack: true,
    isElectrified: true,
    source: "Indian Railways / CRIS RBS",
    verified: true,
    lastVerified: "2026-08-24",
  },
  {
    id: "BZU-AMLA",
    fromCode: "BZU",
    toCode: "AMLA",
    distanceKm: 23.0,
    lineName: "Grand Trunk Route",
    zone: "CR",
    isDoubleTrack: true,
    isElectrified: true,
    source: "Indian Railways / CRIS RBS",
    verified: true,
    lastVerified: "2026-08-24",
  },
  {
    id: "AMLA-CWA",
    fromCode: "AMLA",
    toCode: "CWA",
    distanceKm: 115.0,
    lineName: "Amla-Chhindwara Branch Line",
    zone: "CR",
    isDoubleTrack: false,
    isElectrified: true,
    source: "Indian Railways / CRIS RBS",
    verified: true,
    lastVerified: "2026-08-24",
  },
  {
    id: "AMLA-NGP",
    fromCode: "AMLA",
    toCode: "NGP",
    distanceKm: 168.0,
    lineName: "Grand Trunk Route",
    zone: "CR",
    isDoubleTrack: true,
    isElectrified: true,
    source: "Indian Railways / CRIS RBS",
    verified: true,
    lastVerified: "2026-08-24",
  },
  {
    id: "NGP-WR",
    fromCode: "NGP",
    toCode: "WR",
    distanceKm: 79.0,
    lineName: "Nagpur-Wardha Section",
    zone: "CR",
    isDoubleTrack: true,
    isElectrified: true,
    source: "Indian Railways / CRIS RBS",
    verified: true,
    lastVerified: "2026-08-24",
  },
  {
    id: "WR-BPQ",
    fromCode: "WR",
    toCode: "BPQ",
    distanceKm: 132.0,
    lineName: "Wardha-Balharshah Section",
    zone: "CR",
    isDoubleTrack: true,
    isElectrified: true,
    source: "Indian Railways / CRIS RBS",
    verified: true,
    lastVerified: "2026-08-24",
  },
  {
    id: "BPQ-KZJ",
    fromCode: "BPQ",
    toCode: "KZJ",
    distanceKm: 235.0,
    lineName: "Balharshah-Kazipet Section",
    zone: "SCR",
    isDoubleTrack: true,
    isElectrified: true,
    source: "Indian Railways / CRIS RBS",
    verified: true,
    lastVerified: "2026-08-24",
  },
  {
    id: "KZJ-SC",
    fromCode: "KZJ",
    toCode: "SC",
    distanceKm: 132.0,
    lineName: "Kazipet-Secunderabad Section",
    zone: "SCR",
    isDoubleTrack: true,
    isElectrified: true,
    source: "Indian Railways / CRIS RBS",
    verified: true,
    lastVerified: "2026-08-24",
  },
  {
    id: "SC-HYB",
    fromCode: "SC",
    toCode: "HYB",
    distanceKm: 9.0,
    lineName: "Hyderabad Suburban Section",
    zone: "SCR",
    isDoubleTrack: true,
    isElectrified: true,
    source: "Indian Railways / CRIS RBS",
    verified: true,
    lastVerified: "2026-08-24",
  },
  {
    id: "KZJ-BZA",
    fromCode: "KZJ",
    toCode: "BZA",
    distanceKm: 217.0,
    lineName: "Kazipet-Vijayawada Section",
    zone: "SCR",
    isDoubleTrack: true,
    isElectrified: true,
    source: "Indian Railways / CRIS RBS",
    verified: true,
    lastVerified: "2026-08-24",
  },
  {
    id: "BZA-MAS",
    fromCode: "BZA",
    toCode: "MAS",
    distanceKm: 431.0,
    lineName: "Vijayawada-Chennai Section",
    zone: "SR",
    isDoubleTrack: true,
    isElectrified: true,
    source: "Indian Railways / CRIS RBS",
    verified: true,
    lastVerified: "2026-08-24",
  },

  // ─────────────────────────────────────────────────────────────
  // 3. DELHI - KANPUR - PRAYAGRAJ - DDU - HOWRAH MAIN TRUNK LINE
  // ─────────────────────────────────────────────────────────────
  {
    id: "NDLS-GZB",
    fromCode: "NDLS",
    toCode: "GZB",
    distanceKm: 25.0,
    lineName: "Delhi-Ghaziabad Section",
    zone: "NR",
    isDoubleTrack: true,
    isElectrified: true,
    source: "Indian Railways / CRIS RBS",
    verified: true,
    lastVerified: "2026-08-24",
  },
  {
    id: "ANVT-GZB",
    fromCode: "ANVT",
    toCode: "GZB",
    distanceKm: 13.0,
    lineName: "Anand Vihar Chord",
    zone: "NR",
    isDoubleTrack: true,
    isElectrified: true,
    source: "Indian Railways / CRIS RBS",
    verified: true,
    lastVerified: "2026-08-24",
  },
  {
    id: "DLI-GZB",
    fromCode: "DLI",
    toCode: "GZB",
    distanceKm: 20.0,
    lineName: "Old Delhi-Ghaziabad Section",
    zone: "NR",
    isDoubleTrack: true,
    isElectrified: true,
    source: "Indian Railways / CRIS RBS",
    verified: true,
    lastVerified: "2026-08-24",
  },
  {
    id: "GZB-ALJN",
    fromCode: "GZB",
    toCode: "ALJN",
    distanceKm: 106.0,
    lineName: "Ghaziabad-Aligarh Section",
    zone: "NCR",
    isDoubleTrack: true,
    isElectrified: true,
    source: "Indian Railways / CRIS RBS",
    verified: true,
    lastVerified: "2026-08-24",
  },
  {
    id: "ALJN-TDL",
    fromCode: "ALJN",
    toCode: "TDL",
    distanceKm: 78.0,
    lineName: "Aligarh-Tundla Section",
    zone: "NCR",
    isDoubleTrack: true,
    isElectrified: true,
    source: "Indian Railways / CRIS RBS",
    verified: true,
    lastVerified: "2026-08-24",
  },
  {
    id: "TDL-AF",
    fromCode: "TDL",
    toCode: "AF",
    distanceKm: 23.0,
    lineName: "Tundla-Agra Fort Branch",
    zone: "NCR",
    isDoubleTrack: true,
    isElectrified: true,
    source: "Indian Railways / CRIS RBS",
    verified: true,
    lastVerified: "2026-08-24",
  },
  {
    id: "TDL-ETW",
    fromCode: "TDL",
    toCode: "ETW",
    distanceKm: 92.0,
    lineName: "Tundla-Etawah Section",
    zone: "NCR",
    isDoubleTrack: true,
    isElectrified: true,
    source: "Indian Railways / CRIS RBS",
    verified: true,
    lastVerified: "2026-08-24",
  },
  {
    id: "ETW-CNB",
    fromCode: "ETW",
    toCode: "CNB",
    distanceKm: 139.0,
    lineName: "Etawah-Kanpur Section",
    zone: "NCR",
    isDoubleTrack: true,
    isElectrified: true,
    source: "Indian Railways / CRIS RBS",
    verified: true,
    lastVerified: "2026-08-24",
  },
  {
    id: "CNB-PRYJ",
    fromCode: "CNB",
    toCode: "PRYJ",
    distanceKm: 195.0,
    lineName: "Kanpur-Prayagraj Main Line",
    zone: "NCR",
    isDoubleTrack: true,
    isElectrified: true,
    source: "Indian Railways / CRIS RBS",
    verified: true,
    lastVerified: "2026-08-24",
  },
  {
    id: "PRYJ-DDU",
    fromCode: "PRYJ",
    toCode: "DDU",
    distanceKm: 152.0,
    lineName: "Prayagraj-Pt Deen Dayal Upadhyaya Section",
    zone: "NCR",
    isDoubleTrack: true,
    isElectrified: true,
    source: "Indian Railways / CRIS RBS",
    verified: true,
    lastVerified: "2026-08-24",
  },
  {
    id: "PRYJ-BSB",
    fromCode: "PRYJ",
    toCode: "BSB",
    distanceKm: 124.0,
    lineName: "Prayagraj-Varanasi Chord",
    zone: "NR",
    isDoubleTrack: true,
    isElectrified: true,
    source: "Indian Railways / CRIS RBS",
    verified: true,
    lastVerified: "2026-08-24",
  },
  {
    id: "BSB-DDU",
    fromCode: "BSB",
    toCode: "DDU",
    distanceKm: 18.0,
    lineName: "Varanasi-Mughalsarai Chord",
    zone: "ECR",
    isDoubleTrack: true,
    isElectrified: true,
    source: "Indian Railways / CRIS RBS",
    verified: true,
    lastVerified: "2026-08-24",
  },
  {
    id: "DDU-PNBE",
    fromCode: "DDU",
    toCode: "PNBE",
    distanceKm: 212.0,
    lineName: "DDU-Patna Main Line",
    zone: "ECR",
    isDoubleTrack: true,
    isElectrified: true,
    source: "Indian Railways / CRIS RBS",
    verified: true,
    lastVerified: "2026-08-24",
  },
  {
    id: "DDU-GAYA",
    fromCode: "DDU",
    toCode: "GAYA",
    distanceKm: 205.0,
    lineName: "Grand Chord Line (DDU-Gaya)",
    zone: "ECR",
    isDoubleTrack: true,
    isElectrified: true,
    source: "Indian Railways / CRIS RBS",
    verified: true,
    lastVerified: "2026-08-24",
  },
  {
    id: "GAYA-DHN",
    fromCode: "GAYA",
    toCode: "DHN",
    distanceKm: 201.0,
    lineName: "Grand Chord Line (Gaya-Dhanbad)",
    zone: "ECR",
    isDoubleTrack: true,
    isElectrified: true,
    source: "Indian Railways / CRIS RBS",
    verified: true,
    lastVerified: "2026-08-24",
  },
  {
    id: "DHN-ASN",
    fromCode: "DHN",
    toCode: "ASN",
    distanceKm: 59.0,
    lineName: "Grand Chord Line (Dhanbad-Asansol)",
    zone: "ER",
    isDoubleTrack: true,
    isElectrified: true,
    source: "Indian Railways / CRIS RBS",
    verified: true,
    lastVerified: "2026-08-24",
  },
  {
    id: "PNBE-ASN",
    fromCode: "PNBE",
    toCode: "ASN",
    distanceKm: 331.0,
    lineName: "Patna-Asansol Main Line",
    zone: "ER",
    isDoubleTrack: true,
    isElectrified: true,
    source: "Indian Railways / CRIS RBS",
    verified: true,
    lastVerified: "2026-08-24",
  },
  {
    id: "ASN-HWH",
    fromCode: "ASN",
    toCode: "HWH",
    distanceKm: 200.0,
    lineName: "Asansol-Howrah Main Section",
    zone: "ER",
    isDoubleTrack: true,
    isElectrified: true,
    source: "Indian Railways / CRIS RBS",
    verified: true,
    lastVerified: "2026-08-24",
  },
  {
    id: "HWH-SDAH",
    fromCode: "HWH",
    toCode: "SDAH",
    distanceKm: 5.0,
    lineName: "Kolkata City Connection",
    zone: "ER",
    isDoubleTrack: true,
    isElectrified: true,
    source: "Indian Railways / CRIS RBS",
    verified: true,
    lastVerified: "2026-08-24",
  },

  // ─────────────────────────────────────────────────────────────
  // 4. NORTHERN CORRIDORS (Delhi - Moradabad - Lucknow - Gorakhpur / Ayodhya)
  // ─────────────────────────────────────────────────────────────
  {
    id: "GZB-MB",
    fromCode: "GZB",
    toCode: "MB",
    distanceKm: 141.0,
    lineName: "Ghaziabad-Moradabad Section",
    zone: "NR",
    isDoubleTrack: true,
    isElectrified: true,
    source: "Indian Railways / CRIS RBS",
    verified: true,
    lastVerified: "2026-08-24",
  },
  {
    id: "MB-BE",
    fromCode: "MB",
    toCode: "BE",
    distanceKm: 90.0,
    lineName: "Moradabad-Bareilly Section",
    zone: "NR",
    isDoubleTrack: true,
    isElectrified: true,
    source: "Indian Railways / CRIS RBS",
    verified: true,
    lastVerified: "2026-08-24",
  },
  {
    id: "BE-LKO",
    fromCode: "BE",
    toCode: "LKO",
    distanceKm: 235.0,
    lineName: "Bareilly-Lucknow Main Line",
    zone: "NR",
    isDoubleTrack: true,
    isElectrified: true,
    source: "Indian Railways / CRIS RBS",
    verified: true,
    lastVerified: "2026-08-24",
  },
  {
    id: "LKO-CNB",
    fromCode: "LKO",
    toCode: "CNB",
    distanceKm: 72.0,
    lineName: "Lucknow-Kanpur Section",
    zone: "NR",
    isDoubleTrack: true,
    isElectrified: true,
    source: "Indian Railways / CRIS RBS",
    verified: true,
    lastVerified: "2026-08-24",
  },
  {
    id: "LKO-AYC",
    fromCode: "LKO",
    toCode: "AYC",
    distanceKm: 128.0,
    lineName: "Lucknow-Ayodhya Cantt Section",
    zone: "NR",
    isDoubleTrack: true,
    isElectrified: true,
    source: "Indian Railways / CRIS RBS",
    verified: true,
    lastVerified: "2026-08-24",
  },
  {
    id: "AYC-AY",
    fromCode: "AYC",
    toCode: "AY",
    distanceKm: 8.0,
    lineName: "Ayodhya Twin Stations Link",
    zone: "NR",
    isDoubleTrack: true,
    isElectrified: true,
    source: "Indian Railways / CRIS RBS",
    verified: true,
    lastVerified: "2026-08-24",
  },
  {
    id: "AY-BSB",
    fromCode: "AY",
    toCode: "BSB",
    distanceKm: 189.0,
    lineName: "Ayodhya-Varanasi Section",
    zone: "NR",
    isDoubleTrack: true,
    isElectrified: true,
    source: "Indian Railways / CRIS RBS",
    verified: true,
    lastVerified: "2026-08-24",
  },
  {
    id: "LKO-BSB",
    fromCode: "LKO",
    toCode: "BSB",
    distanceKm: 284.0,
    lineName: "Lucknow-Sultanpur-Varanasi Line",
    zone: "NR",
    isDoubleTrack: true,
    isElectrified: true,
    source: "Indian Railways / CRIS RBS",
    verified: true,
    lastVerified: "2026-08-24",
  },
  {
    id: "LKO-GKP",
    fromCode: "LKO",
    toCode: "GKP",
    distanceKm: 279.0,
    lineName: "Lucknow-Gorakhpur Line (via Gonda)",
    zone: "NER",
    isDoubleTrack: true,
    isElectrified: true,
    source: "Indian Railways / CRIS RBS",
    verified: true,
    lastVerified: "2026-08-24",
  },
  {
    id: "GKP-CPR",
    fromCode: "GKP",
    toCode: "CPR",
    distanceKm: 180.0,
    lineName: "Gorakhpur-Chhapra Section",
    zone: "NER",
    isDoubleTrack: true,
    isElectrified: true,
    source: "Indian Railways / CRIS RBS",
    verified: true,
    lastVerified: "2026-08-24",
  },
  {
    id: "CPR-PNBE",
    fromCode: "CPR",
    toCode: "PNBE",
    distanceKm: 65.0,
    lineName: "Chhapra-Patna Section",
    zone: "ECR",
    isDoubleTrack: true,
    isElectrified: true,
    source: "Indian Railways / CRIS RBS",
    verified: true,
    lastVerified: "2026-08-24",
  },

  // ─────────────────────────────────────────────────────────────
  // 5. DELHI - KOTA - RATLAM - VADODARA - MUMBAI CENTRAL (Delhi-Mumbai Trunk)
  // ─────────────────────────────────────────────────────────────
  {
    id: "MTJ-BTE",
    fromCode: "MTJ",
    toCode: "BTE",
    distanceKm: 34.0,
    lineName: "Mathura-Bharatpur Section",
    zone: "WCR",
    isDoubleTrack: true,
    isElectrified: true,
    source: "Indian Railways / CRIS RBS",
    verified: true,
    lastVerified: "2026-08-24",
  },
  {
    id: "BTE-SWM",
    fromCode: "BTE",
    toCode: "SWM",
    distanceKm: 184.0,
    lineName: "Bharatpur-Sawai Madhopur Section",
    zone: "WCR",
    isDoubleTrack: true,
    isElectrified: true,
    source: "Indian Railways / CRIS RBS",
    verified: true,
    lastVerified: "2026-08-24",
  },
  {
    id: "SWM-KOTA",
    fromCode: "SWM",
    toCode: "KOTA",
    distanceKm: 108.0,
    lineName: "Sawai Madhopur-Kota Section",
    zone: "WCR",
    isDoubleTrack: true,
    isElectrified: true,
    source: "Indian Railways / CRIS RBS",
    verified: true,
    lastVerified: "2026-08-24",
  },
  {
    id: "KOTA-NAD",
    fromCode: "KOTA",
    toCode: "NAD",
    distanceKm: 227.0,
    lineName: "Kota-Nagda Section",
    zone: "WCR",
    isDoubleTrack: true,
    isElectrified: true,
    source: "Indian Railways / CRIS RBS",
    verified: true,
    lastVerified: "2026-08-24",
  },
  {
    id: "NAD-RTM",
    fromCode: "NAD",
    toCode: "RTM",
    distanceKm: 41.0,
    lineName: "Nagda-Ratlam Section",
    zone: "WR",
    isDoubleTrack: true,
    isElectrified: true,
    source: "Indian Railways / CRIS RBS",
    verified: true,
    lastVerified: "2026-08-24",
  },
  {
    id: "NAD-UJN",
    fromCode: "NAD",
    toCode: "UJN",
    distanceKm: 55.0,
    lineName: "Nagda-Ujjain Section",
    zone: "WR",
    isDoubleTrack: true,
    isElectrified: true,
    source: "Indian Railways / CRIS RBS",
    verified: true,
    lastVerified: "2026-08-24",
  },
  {
    id: "UJN-INDB",
    fromCode: "UJN",
    toCode: "INDB",
    distanceKm: 79.0,
    lineName: "Ujjain-Indore Section",
    zone: "WR",
    isDoubleTrack: true,
    isElectrified: true,
    source: "Indian Railways / CRIS RBS",
    verified: true,
    lastVerified: "2026-08-24",
  },
  {
    id: "UJN-BPL",
    fromCode: "UJN",
    toCode: "BPL",
    distanceKm: 183.0,
    lineName: "Ujjain-Bhopal Section",
    zone: "WR",
    isDoubleTrack: true,
    isElectrified: true,
    source: "Indian Railways / CRIS RBS",
    verified: true,
    lastVerified: "2026-08-24",
  },
  {
    id: "RTM-BRC",
    fromCode: "RTM",
    toCode: "BRC",
    distanceKm: 261.0,
    lineName: "Ratlam-Vadodara Main Line",
    zone: "WR",
    isDoubleTrack: true,
    isElectrified: true,
    source: "Indian Railways / CRIS RBS",
    verified: true,
    lastVerified: "2026-08-24",
  },
  {
    id: "BRC-ADI",
    fromCode: "BRC",
    toCode: "ADI",
    distanceKm: 100.0,
    lineName: "Vadodara-Ahmedabad Section",
    zone: "WR",
    isDoubleTrack: true,
    isElectrified: true,
    source: "Indian Railways / CRIS RBS",
    verified: true,
    lastVerified: "2026-08-24",
  },
  {
    id: "BRC-ST",
    fromCode: "BRC",
    toCode: "ST",
    distanceKm: 130.0,
    lineName: "Vadodara-Surat Section",
    zone: "WR",
    isDoubleTrack: true,
    isElectrified: true,
    source: "Indian Railways / CRIS RBS",
    verified: true,
    lastVerified: "2026-08-24",
  },
  {
    id: "ST-BL",
    fromCode: "ST",
    toCode: "BL",
    distanceKm: 69.0,
    lineName: "Surat-Valsad Section",
    zone: "WR",
    isDoubleTrack: true,
    isElectrified: true,
    source: "Indian Railways / CRIS RBS",
    verified: true,
    lastVerified: "2026-08-24",
  },
  {
    id: "BL-BVI",
    fromCode: "BL",
    toCode: "BVI",
    distanceKm: 166.0,
    lineName: "Valsad-Borivali Section",
    zone: "WR",
    isDoubleTrack: true,
    isElectrified: true,
    source: "Indian Railways / CRIS RBS",
    verified: true,
    lastVerified: "2026-08-24",
  },
  {
    id: "BVI-MMCT",
    fromCode: "BVI",
    toCode: "MMCT",
    distanceKm: 23.0,
    lineName: "Mumbai Suburban Western Line",
    zone: "WR",
    isDoubleTrack: true,
    isElectrified: true,
    source: "Indian Railways / CRIS RBS",
    verified: true,
    lastVerified: "2026-08-24",
  },
  {
    id: "BVI-BDTS",
    fromCode: "BVI",
    toCode: "BDTS",
    distanceKm: 19.0,
    lineName: "Bandra Terminus Access Line",
    zone: "WR",
    isDoubleTrack: true,
    isElectrified: true,
    source: "Indian Railways / CRIS RBS",
    verified: true,
    lastVerified: "2026-08-24",
  },

  // ─────────────────────────────────────────────────────────────
  // 6. DELHI - JAIPUR - AJMER - AHMEDABAD (Rajasthan Main Line)
  // ─────────────────────────────────────────────────────────────
  {
    id: "NDLS-DEC",
    fromCode: "NDLS",
    toCode: "DEC",
    distanceKm: 15.0,
    lineName: "Delhi-Delhi Cantt Section",
    zone: "NR",
    isDoubleTrack: true,
    isElectrified: true,
    source: "Indian Railways / CRIS RBS",
    verified: true,
    lastVerified: "2026-08-24",
  },
  {
    id: "DEC-RE",
    fromCode: "DEC",
    toCode: "RE",
    distanceKm: 68.0,
    lineName: "Delhi-Rewari Section",
    zone: "NR",
    isDoubleTrack: true,
    isElectrified: true,
    source: "Indian Railways / CRIS RBS",
    verified: true,
    lastVerified: "2026-08-24",
  },
  {
    id: "RE-AWR",
    fromCode: "RE",
    toCode: "AWR",
    distanceKm: 74.0,
    lineName: "Rewari-Alwar Section",
    zone: "NWR",
    isDoubleTrack: true,
    isElectrified: true,
    source: "Indian Railways / CRIS RBS",
    verified: true,
    lastVerified: "2026-08-24",
  },
  {
    id: "AWR-JP",
    fromCode: "AWR",
    toCode: "JP",
    distanceKm: 150.0,
    lineName: "Alwar-Jaipur Section",
    zone: "NWR",
    isDoubleTrack: true,
    isElectrified: true,
    source: "Indian Railways / CRIS RBS",
    verified: true,
    lastVerified: "2026-08-24",
  },
  {
    id: "JP-AII",
    fromCode: "JP",
    toCode: "AII",
    distanceKm: 135.0,
    lineName: "Jaipur-Ajmer Section",
    zone: "NWR",
    isDoubleTrack: true,
    isElectrified: true,
    source: "Indian Railways / CRIS RBS",
    verified: true,
    lastVerified: "2026-08-24",
  },
  {
    id: "AII-ABR",
    fromCode: "AII",
    toCode: "ABR",
    distanceKm: 288.0,
    lineName: "Ajmer-Abu Road Section",
    zone: "NWR",
    isDoubleTrack: true,
    isElectrified: true,
    source: "Indian Railways / CRIS RBS",
    verified: true,
    lastVerified: "2026-08-24",
  },
  {
    id: "ABR-ADI",
    fromCode: "ABR",
    toCode: "ADI",
    distanceKm: 188.0,
    lineName: "Abu Road-Ahmedabad Section",
    zone: "WR",
    isDoubleTrack: true,
    isElectrified: true,
    source: "Indian Railways / CRIS RBS",
    verified: true,
    lastVerified: "2026-08-24",
  },

  // ─────────────────────────────────────────────────────────────
  // 7. MUMBAI - PUNE - SOLAPUR - WADI - GUNTAKAL - BENGALURU
  // ─────────────────────────────────────────────────────────────
  {
    id: "CSMT-KYN",
    fromCode: "CSMT",
    toCode: "KYN",
    distanceKm: 54.0,
    lineName: "Mumbai Central Suburban Main Line",
    zone: "CR",
    isDoubleTrack: true,
    isElectrified: true,
    source: "Indian Railways / CRIS RBS",
    verified: true,
    lastVerified: "2026-08-24",
  },
  {
    id: "KYN-PUNE",
    fromCode: "KYN",
    toCode: "PUNE",
    distanceKm: 138.0,
    lineName: "Kalyan-Pune Bhor Ghat Line",
    zone: "CR",
    isDoubleTrack: true,
    isElectrified: true,
    source: "Indian Railways / CRIS RBS",
    verified: true,
    lastVerified: "2026-08-24",
  },
  {
    id: "PUNE-SUR",
    fromCode: "PUNE",
    toCode: "SUR",
    distanceKm: 266.0,
    lineName: "Pune-Solapur Section",
    zone: "CR",
    isDoubleTrack: true,
    isElectrified: true,
    source: "Indian Railways / CRIS RBS",
    verified: true,
    lastVerified: "2026-08-24",
  },
  {
    id: "SUR-WADI",
    fromCode: "SUR",
    toCode: "WADI",
    distanceKm: 150.0,
    lineName: "Solapur-Wadi Section",
    zone: "CR",
    isDoubleTrack: true,
    isElectrified: true,
    source: "Indian Railways / CRIS RBS",
    verified: true,
    lastVerified: "2026-08-24",
  },
  {
    id: "WADI-GTL",
    fromCode: "WADI",
    toCode: "GTL",
    distanceKm: 230.0,
    lineName: "Wadi-Guntakal Section",
    zone: "SCR",
    isDoubleTrack: true,
    isElectrified: true,
    source: "Indian Railways / CRIS RBS",
    verified: true,
    lastVerified: "2026-08-24",
  },
  {
    id: "GTL-SBC",
    fromCode: "GTL",
    toCode: "SBC",
    distanceKm: 301.0,
    lineName: "Guntakal-Bengaluru Section",
    zone: "SWR",
    isDoubleTrack: true,
    isElectrified: true,
    source: "Indian Railways / CRIS RBS",
    verified: true,
    lastVerified: "2026-08-24",
  },

  // ─────────────────────────────────────────────────────────────
  // 8. HOWRAH - BHUBANESWAR - VISAKHAPATNAM - VIJAYAWADA - CHENNAI
  // ─────────────────────────────────────────────────────────────
  {
    id: "HWH-KGP",
    fromCode: "HWH",
    toCode: "KGP",
    distanceKm: 115.0,
    lineName: "Howrah-Kharagpur Section",
    zone: "SER",
    isDoubleTrack: true,
    isElectrified: true,
    source: "Indian Railways / CRIS RBS",
    verified: true,
    lastVerified: "2026-08-24",
  },
  {
    id: "KGP-BBS",
    fromCode: "KGP",
    toCode: "BBS",
    distanceKm: 322.0,
    lineName: "Kharagpur-Bhubaneswar Section",
    zone: "ECoR",
    isDoubleTrack: true,
    isElectrified: true,
    source: "Indian Railways / CRIS RBS",
    verified: true,
    lastVerified: "2026-08-24",
  },
  {
    id: "BBS-VSKP",
    fromCode: "BBS",
    toCode: "VSKP",
    distanceKm: 444.0,
    lineName: "Bhubaneswar-Visakhapatnam Section",
    zone: "ECoR",
    isDoubleTrack: true,
    isElectrified: true,
    source: "Indian Railways / CRIS RBS",
    verified: true,
    lastVerified: "2026-08-24",
  },
  {
    id: "VSKP-BZA",
    fromCode: "VSKP",
    toCode: "BZA",
    distanceKm: 350.0,
    lineName: "Visakhapatnam-Vijayawada Section",
    zone: "SCR",
    isDoubleTrack: true,
    isElectrified: true,
    source: "Indian Railways / CRIS RBS",
    verified: true,
    lastVerified: "2026-08-24",
  },

  // ─────────────────────────────────────────────────────────────
  // 9. MUMBAI - NAGPUR - RAIPUR - BILASPUR - HOWRAH TRUNK
  // ─────────────────────────────────────────────────────────────
  {
    id: "KYN-BSL",
    fromCode: "KYN",
    toCode: "BSL",
    distanceKm: 391.0,
    lineName: "Kalyan-Bhusaval Thal Ghat Line",
    zone: "CR",
    isDoubleTrack: true,
    isElectrified: true,
    source: "Indian Railways / CRIS RBS",
    verified: true,
    lastVerified: "2026-08-24",
  },
  {
    id: "BSL-NGP",
    fromCode: "BSL",
    toCode: "NGP",
    distanceKm: 392.0,
    lineName: "Bhusaval-Nagpur Main Line",
    zone: "CR",
    isDoubleTrack: true,
    isElectrified: true,
    source: "Indian Railways / CRIS RBS",
    verified: true,
    lastVerified: "2026-08-24",
  },
  {
    id: "NGP-R",
    fromCode: "NGP",
    toCode: "R",
    distanceKm: 302.0,
    lineName: "Nagpur-Raipur Line",
    zone: "SECR",
    isDoubleTrack: true,
    isElectrified: true,
    source: "Indian Railways / CRIS RBS",
    verified: true,
    lastVerified: "2026-08-24",
  },
  {
    id: "R-BSP",
    fromCode: "R",
    toCode: "BSP",
    distanceKm: 111.0,
    lineName: "Raipur-Bilaspur Section",
    zone: "SECR",
    isDoubleTrack: true,
    isElectrified: true,
    source: "Indian Railways / CRIS RBS",
    verified: true,
    lastVerified: "2026-08-24",
  },
  {
    id: "BSP-TATA",
    fromCode: "BSP",
    toCode: "TATA",
    distanceKm: 470.0,
    lineName: "Bilaspur-Tatanagar Section",
    zone: "SER",
    isDoubleTrack: true,
    isElectrified: true,
    source: "Indian Railways / CRIS RBS",
    verified: true,
    lastVerified: "2026-08-24",
  },
  {
    id: "TATA-KGP",
    fromCode: "TATA",
    toCode: "KGP",
    distanceKm: 134.0,
    lineName: "Tatanagar-Kharagpur Section",
    zone: "SER",
    isDoubleTrack: true,
    isElectrified: true,
    source: "Indian Railways / CRIS RBS",
    verified: true,
    lastVerified: "2026-08-24",
  },

  // ─────────────────────────────────────────────────────────────
  // 10. PUNJAB, HARYANA & J&K (Delhi - Ambala - Ludhiana - Amritsar / Jammu)
  // ─────────────────────────────────────────────────────────────
  {
    id: "NDLS-PNP",
    fromCode: "NDLS",
    toCode: "PNP",
    distanceKm: 89.0,
    lineName: "Delhi-Panipat Section",
    zone: "NR",
    isDoubleTrack: true,
    isElectrified: true,
    source: "Indian Railways / CRIS RBS",
    verified: true,
    lastVerified: "2026-08-24",
  },
  {
    id: "PNP-UMB",
    fromCode: "PNP",
    toCode: "UMB",
    distanceKm: 109.0,
    lineName: "Panipat-Ambala Cantt Section",
    zone: "NR",
    isDoubleTrack: true,
    isElectrified: true,
    source: "Indian Railways / CRIS RBS",
    verified: true,
    lastVerified: "2026-08-24",
  },
  {
    id: "UMB-CDG",
    fromCode: "UMB",
    toCode: "CDG",
    distanceKm: 45.0,
    lineName: "Ambala-Chandigarh Section",
    zone: "NR",
    isDoubleTrack: true,
    isElectrified: true,
    source: "Indian Railways / CRIS RBS",
    verified: true,
    lastVerified: "2026-08-24",
  },
  {
    id: "UMB-LDH",
    fromCode: "UMB",
    toCode: "LDH",
    distanceKm: 114.0,
    lineName: "Ambala-Ludhiana Section",
    zone: "NR",
    isDoubleTrack: true,
    isElectrified: true,
    source: "Indian Railways / CRIS RBS",
    verified: true,
    lastVerified: "2026-08-24",
  },
  {
    id: "LDH-JUC",
    fromCode: "LDH",
    toCode: "JUC",
    distanceKm: 57.0,
    lineName: "Ludhiana-Jalandhar City Section",
    zone: "NR",
    isDoubleTrack: true,
    isElectrified: true,
    source: "Indian Railways / CRIS RBS",
    verified: true,
    lastVerified: "2026-08-24",
  },
  {
    id: "JUC-ASR",
    fromCode: "JUC",
    toCode: "ASR",
    distanceKm: 79.0,
    lineName: "Jalandhar-Amritsar Section",
    zone: "NR",
    isDoubleTrack: true,
    isElectrified: true,
    source: "Indian Railways / CRIS RBS",
    verified: true,
    lastVerified: "2026-08-24",
  },
  {
    id: "JUC-JAT",
    fromCode: "JUC",
    toCode: "JAT",
    distanceKm: 213.0,
    lineName: "Jalandhar-Jammu Tawi Section",
    zone: "NR",
    isDoubleTrack: true,
    isElectrified: true,
    source: "Indian Railways / CRIS RBS",
    verified: true,
    lastVerified: "2026-08-24",
  },
  {
    id: "JAT-SVDK",
    fromCode: "JAT",
    toCode: "SVDK",
    distanceKm: 78.0,
    lineName: "Jammu-Shri Mata Vaishno Devi Katra Section",
    zone: "NR",
    isDoubleTrack: false,
    isElectrified: true,
    source: "Indian Railways / CRIS RBS",
    verified: true,
    lastVerified: "2026-08-24",
  },

  // ─────────────────────────────────────────────────────────────
  // 11. REGIONAL BRANCHES (Jhansi - Kanpur, Jhansi - Manikpur, Gwalior - Bhind)
  // ─────────────────────────────────────────────────────────────
  {
    id: "JHS-CNB",
    fromCode: "JHS",
    toCode: "CNB",
    distanceKm: 220.0,
    lineName: "Jhansi-Kanpur Section (via Orai)",
    zone: "NCR",
    isDoubleTrack: true,
    isElectrified: true,
    source: "Indian Railways / CRIS RBS",
    verified: true,
    lastVerified: "2026-08-24",
  },
  {
    id: "JHS-BNDA",
    fromCode: "JHS",
    toCode: "BNDA",
    distanceKm: 191.0,
    lineName: "Jhansi-Banda Section (via Mahoba)",
    zone: "NCR",
    isDoubleTrack: false,
    isElectrified: true,
    source: "Indian Railways / CRIS RBS",
    verified: true,
    lastVerified: "2026-08-24",
  },
  {
    id: "BNDA-MKP",
    fromCode: "BNDA",
    toCode: "MKP",
    distanceKm: 100.0,
    lineName: "Banda-Manikpur Section",
    zone: "NCR",
    isDoubleTrack: false,
    isElectrified: true,
    source: "Indian Railways / CRIS RBS",
    verified: true,
    lastVerified: "2026-08-24",
  },
  {
    id: "MKP-PRYJ",
    fromCode: "MKP",
    toCode: "PRYJ",
    distanceKm: 100.0,
    lineName: "Manikpur-Prayagraj Section",
    zone: "NCR",
    isDoubleTrack: true,
    isElectrified: true,
    source: "Indian Railways / CRIS RBS",
    verified: true,
    lastVerified: "2026-08-24",
  },
];

