export interface StationModel {
  code: string;
  name: string;
  city: string;
  state: string;
  zone: string;
  isPopular: boolean;
  keywords?: string[];
}

export const generateStationKeywords = (station: StationModel): string[] => {
  const set = new Set<string>();
  const addVariations = (text?: string) => {
    if (!text) return;
    const clean = text.toLowerCase().trim();
    set.add(clean);
    // Prefixes from 2 characters upwards
    for (let i = 2; i <= clean.length; i++) {
      set.add(clean.slice(0, i));
    }
    // Individual words and their prefixes
    const words = clean.split(/[\s\-()\/,]+/);
    for (const w of words) {
      if (w.length >= 2) {
        set.add(w);
        for (let i = 2; i <= w.length; i++) {
          set.add(w.slice(0, i));
        }
      }
    }
  };

  addVariations(station.code);
  addVariations(station.name);
  addVariations(station.city);
  addVariations(station.state);

  return Array.from(set).slice(0, 100);
};

// Compact station tuple: [code, name, city, state, zone, isPopular]
const RAW_STATIONS: [string, string, string, string, string, number][] = [
  ['NDLS', 'NEW DELHI', 'New Delhi', 'Delhi', 'NR', 1],
  ['NZM', 'HAZRAT NIZAMUDDIN JN', 'New Delhi', 'Delhi', 'NR', 1],
  ['DLI', 'OLD DELHI JN', 'Delhi', 'Delhi', 'NR', 1],
  ['ANVT', 'ANAND VIHAR TERMINAL', 'Delhi', 'Delhi', 'NR', 1],
  ['DEC', 'DELHI CANTT', 'Delhi', 'Delhi', 'NR', 1],
  ['DEE', 'DELHI SARAI ROHILLA', 'Delhi', 'Delhi', 'NR', 1],
  ['MRA', 'MORENA', 'Morena', 'Madhya Pradesh', 'NCR', 1],
  ['GWL', 'GWALIOR JN', 'Gwalior', 'Madhya Pradesh', 'NCR', 1],
  ['DBA', 'DABRA', 'Dabra', 'Madhya Pradesh', 'NCR', 0],
  ['AGC', 'AGRA CANTT', 'Agra', 'Uttar Pradesh', 'NCR', 1],
  ['AF', 'AGRA FORT', 'Agra', 'Uttar Pradesh', 'NCR', 1],
  ['RKM', 'RAJA KI MANDI', 'Agra', 'Uttar Pradesh', 'NCR', 1],
  ['MTJ', 'MATHURA JN', 'Mathura', 'Uttar Pradesh', 'NCR', 1],
  ['VRBD', 'VRINDAVAN', 'Mathura', 'Uttar Pradesh', 'NCR', 0],
  ['ALJN', 'ALIGARH JN', 'Aligarh', 'Uttar Pradesh', 'NCR', 1],
  ['TDL', 'TUNDLA JN', 'Firozabad', 'Uttar Pradesh', 'NCR', 1],
  ['ETW', 'ETAWAH JN', 'Etawah', 'Uttar Pradesh', 'NCR', 1],
  ['CNB', 'KANPUR CENTRAL', 'Kanpur', 'Uttar Pradesh', 'NCR', 1],
  ['CPA', 'KANPUR ANWRGANJ', 'Kanpur', 'Uttar Pradesh', 'NER', 0],
  ['LKO', 'LUCKNOW CHARBAGH', 'Lucknow', 'Uttar Pradesh', 'NR', 1],
  ['LJN', 'LUCKNOW JN NER', 'Lucknow', 'Uttar Pradesh', 'NER', 1],
  ['BNZ', 'BADSHAHNAGAR', 'Lucknow', 'Uttar Pradesh', 'NER', 0],
  ['PRYJ', 'PRAYAGRAJ JN (ALLAHABAD)', 'Prayagraj', 'Uttar Pradesh', 'NCR', 1],
  ['PRRB', 'PRAYAGRAJ RAMBAG', 'Prayagraj', 'Uttar Pradesh', 'NER', 0],
  ['BSB', 'VARANASI JN', 'Varanasi', 'Uttar Pradesh', 'NR', 1],
  ['BSBS', 'BANARAS (MANDUADIH)', 'Varanasi', 'Uttar Pradesh', 'NER', 1],
  ['DDU', 'PT DEEN DAYAL UPADHYAYA JN (MUGHALSARAI)', 'Chandauli', 'Uttar Pradesh', 'ECR', 1],
  ['GKP', 'GORAKHPUR JN', 'Gorakhpur', 'Uttar Pradesh', 'NER', 1],
  ['BE', 'BAREILLY JN', 'Bareilly', 'Uttar Pradesh', 'NR', 1],
  ['MB', 'MORADABAD JN', 'Moradabad', 'Uttar Pradesh', 'NR', 1],
  ['MTC', 'MEERUT CITY JN', 'Meerut', 'Uttar Pradesh', 'NR', 1],
  ['GZB', 'GHAZIABAD JN', 'Ghaziabad', 'Uttar Pradesh', 'NR', 1],
  ['SRE', 'SAHARANPUR JN', 'Saharanpur', 'Uttar Pradesh', 'NR', 1],
  ['JHS', 'VIRANGANA LAKSHMIBAI (JHANSI)', 'Jhansi', 'Uttar Pradesh', 'NCR', 1],
  ['LIT', 'LALITPUR JN', 'Lalitpur', 'Uttar Pradesh', 'NCR', 0],
  ['BNDA', 'BANDA JN', 'Banda', 'Uttar Pradesh', 'NCR', 0],
  ['MKP', 'MANIKPUR JN', 'Chitrakoot', 'Uttar Pradesh', 'NCR', 0],
  ['AY', 'AYODHYA DHAM JN', 'Ayodhya', 'Uttar Pradesh', 'NR', 1],
  ['AYC', 'AYODHYA CANTT', 'Ayodhya', 'Uttar Pradesh', 'NR', 1],
  ['FD', 'FAIZABAD JN', 'Ayodhya', 'Uttar Pradesh', 'NR', 0],
  ['SLN', 'SULTANPUR JN', 'Sultanpur', 'Uttar Pradesh', 'NR', 0],
  ['JNU', 'JAUNPUR JN', 'Jaunpur', 'Uttar Pradesh', 'NR', 0],
  ['MAU', 'MAU JN', 'Mau', 'Uttar Pradesh', 'NER', 0],
  ['BUI', 'BALLIA', 'Ballia', 'Uttar Pradesh', 'NER', 0],
  ['GD', 'GONDA JN', 'Gonda', 'Uttar Pradesh', 'NER', 0],
  ['BST', 'BASTI', 'Basti', 'Uttar Pradesh', 'NER', 0],
  ['KLD', 'KHALILABAD', 'Sant Kabir Nagar', 'Uttar Pradesh', 'NER', 0],
  ['DEOS', 'DEORIA SADAR', 'Deoria', 'Uttar Pradesh', 'NER', 0],
  ['STP', 'SITAPUR JN', 'Sitapur', 'Uttar Pradesh', 'NER', 0],
  ['SPN', 'SHAHJAHANPUR', 'Shahjahanpur', 'Uttar Pradesh', 'NR', 0],
  ['HRI', 'HARDOI', 'Hardoi', 'Uttar Pradesh', 'NR', 0],
  ['CH', 'CHANDAUSI JN', 'Sambhal', 'Uttar Pradesh', 'NR', 0],
  ['HW', 'HARIDWAR JN', 'Haridwar', 'Uttarakhand', 'NR', 1],
  ['DDN', 'DEHRADUN', 'Dehradun', 'Uttarakhand', 'NR', 1],
  ['RK', 'ROORKEE', 'Roorkee', 'Uttarakhand', 'NR', 1],
  ['KGM', 'KATHGODAM', 'Kathgodam', 'Uttarakhand', 'NER', 1],
  ['LKU', 'LALKUAN JN', 'Nainital', 'Uttarakhand', 'NER', 0],
  ['KLK', 'KALKA', 'Panchkula', 'Haryana', 'NR', 1],
  ['CDG', 'CHANDIGARH JN', 'Chandigarh', 'Chandigarh', 'NR', 1],
  ['UMB', 'AMBALA CANTT JN', 'Ambala', 'Haryana', 'NR', 1],
  ['PNP', 'PANIPAT JN', 'Panipat', 'Haryana', 'NR', 1],
  ['KUN', 'KARNAL', 'Karnal', 'Haryana', 'NR', 0],
  ['KKDE', 'KURUKSHETRA JN', 'Kurukshetra', 'Haryana', 'NR', 0],
  ['ROK', 'ROHTAK JN', 'Rohtak', 'Haryana', 'NR', 0],
  ['HSR', 'HISAR JN', 'Hisar', 'Haryana', 'NWR', 0],
  ['BNW', 'BHIWANI JN', 'Bhiwani', 'Haryana', 'NWR', 0],
  ['RE', 'REWARI JN', 'Rewari', 'Haryana', 'NWR', 1],
  ['LDH', 'LUDHIANA JN', 'Ludhiana', 'Punjab', 'NR', 1],
  ['JUC', 'JALANDHAR CITY JN', 'Jalandhar', 'Punjab', 'NR', 1],
  ['JRC', 'JALANDHAR CANTT', 'Jalandhar', 'Punjab', 'NR', 0],
  ['ASR', 'AMRITSAR JN', 'Amritsar', 'Punjab', 'NR', 1],
  ['BTI', 'BHATINDA JN', 'Bathinda', 'Punjab', 'NR', 1],
  ['PTA', 'PATIALA', 'Patiala', 'Punjab', 'NR', 0],
  ['PGW', 'PHAGWARA JN', 'Phagwara', 'Punjab', 'NR', 0],
  ['BEAS', 'BEAS JN', 'Beas', 'Punjab', 'NR', 0],
  ['PTKC', 'PATHANKOT CANTT', 'Pathankot', 'Punjab', 'NR', 1],
  ['JAT', 'JAMMU TAWI', 'Jammu', 'Jammu & Kashmir', 'NR', 1],
  ['UHP', 'UDHAMPUR', 'Udhampur', 'Jammu & Kashmir', 'NR', 0],
  ['SVDK', 'SMVD KATRA (VAISHNO DEVI)', 'Katra', 'Jammu & Kashmir', 'NR', 1],
  ['CSTM', 'MUMBAI CSMT', 'Mumbai', 'Maharashtra', 'CR', 1],
  ['MMCT', 'MUMBAI CENTRAL', 'Mumbai', 'Maharashtra', 'WR', 1],
  ['BDTS', 'BANDRA TERMINUS', 'Mumbai', 'Maharashtra', 'WR', 1],
  ['LTT', 'LOKMANYA TILAK TERMINUS (KURLA)', 'Mumbai', 'Maharashtra', 'CR', 1],
  ['DR', 'DADAR CR', 'Mumbai', 'Maharashtra', 'CR', 1],
  ['DDR', 'DADAR WR', 'Mumbai', 'Maharashtra', 'WR', 1],
  ['TNA', 'THANE', 'Thane', 'Maharashtra', 'CR', 1],
  ['KYN', 'KALYAN JN', 'Kalyan', 'Maharashtra', 'CR', 1],
  ['BSR', 'VASAI ROAD', 'Vasai', 'Maharashtra', 'WR', 1],
  ['PNVL', 'PANVEL JN', 'Navi Mumbai', 'Maharashtra', 'CR', 1],
  ['PUNE', 'PUNE JN', 'Pune', 'Maharashtra', 'CR', 1],
  ['LNL', 'LONAVALA', 'Lonavala', 'Maharashtra', 'CR', 1],
  ['DD', 'DAUND JN', 'Daund', 'Maharashtra', 'CR', 0],
  ['SUR', 'SOLAPUR JN', 'Solapur', 'Maharashtra', 'CR', 1],
  ['KOP', 'KOLHAPUR SCSMT', 'Kolhapur', 'Maharashtra', 'CR', 1],
  ['MRJ', 'MIRAJ JN', 'Miraj', 'Maharashtra', 'CR', 0],
  ['STR', 'SATARA', 'Satara', 'Maharashtra', 'CR', 0],
  ['NK', 'NASHIK ROAD', 'Nashik', 'Maharashtra', 'CR', 1],
  ['MMR', 'MANMAD JN', 'Manmad', 'Maharashtra', 'CR', 1],
  ['BSL', 'BHUSAVAL JN', 'Bhusawal', 'Maharashtra', 'CR', 1],
  ['JL', 'JALGAON JN', 'Jalgaon', 'Maharashtra', 'CR', 1],
  ['CSN', 'CHALISGAON JN', 'Chalisgaon', 'Maharashtra', 'CR', 0],
  ['NGP', 'NAGPUR JN', 'Nagpur', 'Maharashtra', 'CR', 1],
  ['WR', 'WARDHA JN', 'Wardha', 'Maharashtra', 'CR', 0],
  ['BD', 'BADNERA JN (AMRAVATI)', 'Amravati', 'Maharashtra', 'CR', 0],
  ['AK', 'AKOLA JN', 'Akola', 'Maharashtra', 'CR', 1],
  ['SEG', 'SHEGAON', 'Shegaon', 'Maharashtra', 'CR', 0],
  ['MKU', 'MALKAPUR', 'Malkapur', 'Maharashtra', 'CR', 0],
  ['CD', 'CHANDRAPUR', 'Chandrapur', 'Maharashtra', 'CR', 0],
  ['BPQ', 'BALHARSHAH JN', 'Balharshah', 'Maharashtra', 'CR', 1],
  ['G', 'GONDIA JN', 'Gondia', 'Maharashtra', 'SECR', 1],
  ['AWB', 'AURANGABAD (CHHATRAPATI SAMBHAJINAGAR)', 'Chhatrapati Sambhajinagar', 'Maharashtra', 'SCR', 1],
  ['J', 'JALNA', 'Jalna', 'Maharashtra', 'SCR', 0],
  ['PBN', 'PARBHANI JN', 'Parbhani', 'Maharashtra', 'SCR', 0],
  ['NED', 'HAZUR SAHIB NANDED', 'Nanded', 'Maharashtra', 'SCR', 1],
  ['RN', 'RATNAGIRI', 'Ratnagiri', 'Maharashtra', 'KR', 1],
  ['MAO', 'MADGAON JN (GOA)', 'Madgaon', 'Goa', 'KR', 1],
  ['VSG', 'VASCO DA GAMA', 'Vasco', 'Goa', 'SWR', 1],
  ['KRMI', 'KARMALI', 'Panaji', 'Goa', 'KR', 0],
  ['THVM', 'THIVIM', 'Mapusa', 'Goa', 'KR', 0],
  ['ADI', 'AHMEDABAD JN', 'Ahmedabad', 'Gujarat', 'WR', 1],
  ['SBT', 'SABARMATI JN', 'Ahmedabad', 'Gujarat', 'WR', 0],
  ['BRC', 'VADODARA JN', 'Vadodara', 'Gujarat', 'WR', 1],
  ['ST', 'SURAT', 'Surat', 'Gujarat', 'WR', 1],
  ['UDN', 'UDHNA JN', 'Surat', 'Gujarat', 'WR', 0],
  ['BL', 'VALSAD', 'Valsad', 'Gujarat', 'WR', 0],
  ['VAPI', 'VAPI', 'Vapi', 'Gujarat', 'WR', 1],
  ['BH', 'BHARUCH JN', 'Bharuch', 'Gujarat', 'WR', 0],
  ['ANND', 'ANAND JN', 'Anand', 'Gujarat', 'WR', 1],
  ['ND', 'NADIAD JN', 'Nadiad', 'Gujarat', 'WR', 0],
  ['RJT', 'RAJKOT JN', 'Rajkot', 'Gujarat', 'WR', 1],
  ['JAM', 'JAMNAGAR', 'Jamnagar', 'Gujarat', 'WR', 0],
  ['DWK', 'DWARKA', 'Dwarka', 'Gujarat', 'WR', 1],
  ['OKHA', 'OKHA', 'Okha', 'Gujarat', 'WR', 0],
  ['PBR', 'PORBANDAR', 'Porbandar', 'Gujarat', 'WR', 0],
  ['JND', 'JUNAGADH JN', 'Junagadh', 'Gujarat', 'WR', 0],
  ['VRL', 'VERAVAL JN (SOMNATH)', 'Veraval', 'Gujarat', 'WR', 1],
  ['BVC', 'BHAVNAGAR TERMINUS', 'Bhavnagar', 'Gujarat', 'WR', 0],
  ['GIMB', 'GANDHIDHAM JN', 'Gandhidham', 'Gujarat', 'WR', 1],
  ['BHUJ', 'BHUJ', 'Bhuj', 'Gujarat', 'WR', 1],
  ['PNU', 'PALANPUR JN', 'Palanpur', 'Gujarat', 'WR', 0],
  ['MSH', 'MEHSANA JN', 'Mehsana', 'Gujarat', 'WR', 0],
  ['JP', 'JAIPUR JN', 'Jaipur', 'Rajasthan', 'NWR', 1],
  ['GADJ', 'GANDHINAGAR JAIPUR', 'Jaipur', 'Rajasthan', 'NWR', 0],
  ['DO', 'DAUSA', 'Dausa', 'Rajasthan', 'NWR', 0],
  ['BKI', 'BANDIKUI JN', 'Bandikui', 'Rajasthan', 'NWR', 0],
  ['AWR', 'ALWAR JN', 'Alwar', 'Rajasthan', 'NWR', 1],
  ['AII', 'AJMER JN', 'Ajmer', 'Rajasthan', 'NWR', 1],
  ['KSG', 'KISHANGARH', 'Kishangarh', 'Rajasthan', 'NWR', 0],
  ['FL', 'PHULERA JN', 'Phulera', 'Rajasthan', 'NWR', 0],
  ['JU', 'JODHPUR JN', 'Jodhpur', 'Rajasthan', 'NWR', 1],
  ['BME', 'BARMER', 'Barmer', 'Rajasthan', 'NWR', 0],
  ['JSM', 'JAISALMER', 'Jaisalmer', 'Rajasthan', 'NWR', 1],
  ['BKN', 'BIKANER JN', 'Bikaner', 'Rajasthan', 'NWR', 1],
  ['LGH', 'LALGARH JN', 'Bikaner', 'Rajasthan', 'NWR', 0],
  ['SGNR', 'SHRI GANGANAGAR', 'Sri Ganganagar', 'Rajasthan', 'NWR', 0],
  ['UDZ', 'UDAIPUR CITY', 'Udaipur', 'Rajasthan', 'NWR', 1],
  ['COR', 'CHITTAURGARH JN', 'Chittorgarh', 'Rajasthan', 'WR', 1],
  ['BHL', 'BHILWARA', 'Bhilwara', 'Rajasthan', 'NWR', 0],
  ['KOTA', 'KOTA JN', 'Kota', 'Rajasthan', 'WCR', 1],
  ['SWM', 'SAWAI MADHOPUR JN', 'Sawai Madhopur', 'Rajasthan', 'WCR', 1],
  ['GGC', 'GANGAPUR CITY', 'Gangapur', 'Rajasthan', 'WCR', 0],
  ['HAN', 'HINDAUN CITY', 'Hindaun', 'Rajasthan', 'WCR', 0],
  ['BTE', 'BHARATPUR JN', 'Bharatpur', 'Rajasthan', 'WCR', 1],
  ['ABR', 'ABU ROAD', 'Mount Abu', 'Rajasthan', 'NWR', 1],
  ['FA', 'FALNA', 'Falna', 'Rajasthan', 'NWR', 0],
  ['MJ', 'MARWAR JN', 'Marwar', 'Rajasthan', 'NWR', 0],
  ['BPL', 'BHOPAL JN', 'Bhopal', 'Madhya Pradesh', 'WCR', 1],
  ['RKMP', 'RANI KAMLAPATI (HABIBGANJ)', 'Bhopal', 'Madhya Pradesh', 'WCR', 1],
  ['INDB', 'INDORE JN BG', 'Indore', 'Madhya Pradesh', 'WR', 1],
  ['UJN', 'UJJAIN JN', 'Ujjain', 'Madhya Pradesh', 'WR', 1],
  ['DWX', 'DEWAS JN', 'Dewas', 'Madhya Pradesh', 'WR', 0],
  ['RTM', 'RATLAM JN', 'Ratlam', 'Madhya Pradesh', 'WR', 1],
  ['NMH', 'NEEMUCH', 'Neemuch', 'Madhya Pradesh', 'WR', 0],
  ['MDS', 'MANDASOR', 'Mandsaur', 'Madhya Pradesh', 'WR', 0],
  ['NAD', 'NAGDA JN', 'Nagda', 'Madhya Pradesh', 'WR', 0],
  ['ET', 'ITARSI JN', 'Itarsi', 'Madhya Pradesh', 'WCR', 1],
  ['HBD', 'HOSHANGABAD (NARMADAPURAM)', 'Narmadapuram', 'Madhya Pradesh', 'WCR', 0],
  ['HD', 'HARDA', 'Harda', 'Madhya Pradesh', 'WCR', 0],
  ['KNW', 'KHANDWA JN', 'Khandwa', 'Madhya Pradesh', 'CR', 1],
  ['BAU', 'BURHANPUR', 'Burhanpur', 'Madhya Pradesh', 'CR', 0],
  ['BINA', 'BINA JN', 'Bina', 'Madhya Pradesh', 'WCR', 1],
  ['SGO', 'SAUGOR (SAGAR)', 'Sagar', 'Madhya Pradesh', 'WCR', 0],
  ['DMO', 'DAMOH', 'Damoh', 'Madhya Pradesh', 'WCR', 0],
  ['KMZ', 'KATNI MURWARA', 'Katni', 'Madhya Pradesh', 'WCR', 0],
  ['KTE', 'KATNI JN', 'Katni', 'Madhya Pradesh', 'WCR', 1],
  ['JBP', 'JABALPUR JN', 'Jabalpur', 'Madhya Pradesh', 'WCR', 1],
  ['MML', 'MADAN MAHAL', 'Jabalpur', 'Madhya Pradesh', 'WCR', 0],
  ['MYR', 'MAIHAR', 'Maihar', 'Madhya Pradesh', 'WCR', 0],
  ['STA', 'SATNA JN', 'Satna', 'Madhya Pradesh', 'WCR', 1],
  ['REWA', 'REWA', 'Rewa', 'Madhya Pradesh', 'WCR', 1],
  ['PPI', 'PIPARIYA (PACHMARHI)', 'Pipariya', 'Madhya Pradesh', 'WCR', 1],
  ['GAR', 'GADARWARA', 'Gadarwara', 'Madhya Pradesh', 'WCR', 0],
  ['NU', 'NARSINGHPUR', 'Narsinghpur', 'Madhya Pradesh', 'WCR', 0],
  ['VGLB', 'VGL JHANSI JN', 'Jhansi', 'Uttar Pradesh', 'NCR', 1],
  ['R', 'RAIPUR JN', 'Raipur', 'Chhattisgarh', 'SECR', 1],
  ['BPHB', 'BHILAI POWER HOUSE', 'Bhilai', 'Chhattisgarh', 'SECR', 0],
  ['DURG', 'DURG JN', 'Durg', 'Chhattisgarh', 'SECR', 1],
  ['RJN', 'RAJNANDGAON', 'Rajnandgaon', 'Chhattisgarh', 'SECR', 0],
  ['BSP', 'BILASPUR JN', 'Bilaspur', 'Chhattisgarh', 'SECR', 1],
  ['RIG', 'RAIGARH', 'Raigarh', 'Chhattisgarh', 'SECR', 0],
  ['CPH', 'CHAMPA JN', 'Janjgir Champa', 'Chhattisgarh', 'SECR', 0],
  ['KRBA', 'KORBA', 'Korba', 'Chhattisgarh', 'SECR', 0],
  ['APR', 'ANUPPUR JN', 'Anuppur', 'Madhya Pradesh', 'SECR', 0],
  ['SDL', 'SHAHDOL', 'Shahdol', 'Madhya Pradesh', 'SECR', 0],
  ['UMR', 'UMARIA', 'Umaria', 'Madhya Pradesh', 'SECR', 0],
  ['PNBE', 'PATNA JN', 'Patna', 'Bihar', 'ECR', 1],
  ['PPTA', 'PATLIPUTRA JN', 'Patna', 'Bihar', 'ECR', 1],
  ['DNR', 'DANAPUR', 'Patna', 'Bihar', 'ECR', 1],
  ['RJPB', 'RAJENDRA NAGAR TERMINAL', 'Patna', 'Bihar', 'ECR', 1],
  ['PNC', 'PATNA SAHEB', 'Patna', 'Bihar', 'ECR', 0],
  ['GAYA', 'GAYA JN', 'Gaya', 'Bihar', 'ECR', 1],
  ['MGS', 'MUGHALSARAI (DDU)', 'Chandauli', 'Uttar Pradesh', 'ECR', 1],
  ['BXR', 'BUXAR', 'Buxar', 'Bihar', 'ECR', 0],
  ['ARA', 'ARA JN', 'Bhojpur', 'Bihar', 'ECR', 1],
  ['MFP', 'MUZAFFARPUR JN', 'Muzaffarpur', 'Bihar', 'ECR', 1],
  ['HJP', 'HAJIPUR JN', 'Hajipur', 'Bihar', 'ECR', 1],
  ['SEE', 'SONPUR JN', 'Sonpur', 'Bihar', 'ECR', 0],
  ['CPR', 'CHHAPRA JN', 'Chhapra', 'Bihar', 'NER', 1],
  ['SV', 'SIWAN JN', 'Siwan', 'Bihar', 'NER', 0],
  ['SPJ', 'SAMASTIPUR JN', 'Samastipur', 'Bihar', 'ECR', 1],
  ['DBG', 'DARBHANGA JN', 'Darbhanga', 'Bihar', 'ECR', 1],
  ['JYG', 'JAYNAGAR', 'Madhubani', 'Bihar', 'ECR', 0],
  ['RXL', 'RAXAUL JN', 'East Champaran', 'Bihar', 'ECR', 0],
  ['BGU', 'BAIRGANIA', 'Sitamarhi', 'Bihar', 'ECR', 0],
  ['SMI', 'SITAMARHI JN', 'Sitamarhi', 'Bihar', 'ECR', 0],
  ['BGS', 'BEGUSARAI', 'Begusarai', 'Bihar', 'ECR', 0],
  ['BJU', 'BARAUNI JN', 'Barauni', 'Bihar', 'ECR', 1],
  ['KGG', 'KHAGARIA JN', 'Khagaria', 'Bihar', 'ECR', 0],
  ['MNE', 'MANSI JN', 'Khagaria', 'Bihar', 'ECR', 0],
  ['NNA', 'NAUGACHIA', 'Bhagalpur', 'Bihar', 'ECR', 0],
  ['KIR', 'KATIHAR JN', 'Katihar', 'Bihar', 'NFR', 1],
  ['BGP', 'BHAGALPUR JN', 'Bhagalpur', 'Bihar', 'ER', 1],
  ['JMP', 'JAMALPUR JN', 'Munger', 'Bihar', 'ER', 0],
  ['KIUL', 'KIUL JN', 'Lakhisarai', 'Bihar', 'ECR', 0],
  ['MKA', 'MOKAMA JN', 'Mokama', 'Bihar', 'ECR', 0],
  ['JAJ', 'JHAJHA', 'Jamui', 'Bihar', 'ECR', 0],
  ['JSME', 'JASIDIH JN (DEOGHAR)', 'Deoghar', 'Jharkhand', 'ER', 1],
  ['MDP', 'MADHUPUR JN', 'Deoghar', 'Jharkhand', 'ER', 0],
  ['CRJ', 'CHITTARANJAN', 'Paschim Bardhaman', 'West Bengal', 'ER', 0],
  ['DHN', 'DHANBAD JN', 'Dhanbad', 'Jharkhand', 'ECR', 1],
  ['GMO', 'NSC BOSE J GOMOH', 'Dhanbad', 'Jharkhand', 'ECR', 0],
  ['BKSC', 'BOKARO STEEL CITY', 'Bokaro', 'Jharkhand', 'SER', 1],
  ['RNC', 'RANCHI JN', 'Ranchi', 'Jharkhand', 'SER', 1],
  ['HTE', 'HATIA', 'Ranchi', 'Jharkhand', 'SER', 0],
  ['MURI', 'MURI JN', 'Ranchi', 'Jharkhand', 'SER', 0],
  ['TATA', 'TATANAGAR JN (JAMSHEDPUR)', 'Jamshedpur', 'Jharkhand', 'SER', 1],
  ['CKP', 'CHAKRADHARPUR', 'West Singhbhum', 'Jharkhand', 'SER', 0],
  ['ROU', 'ROURKELA JN', 'Rourkela', 'Odisha', 'SER', 1],
  ['JSG', 'JHARSUGUDA JN', 'Jharsuguda', 'Odisha', 'SECR', 1],
  ['SBP', 'SAMBALPUR JN', 'Sambalpur', 'Odisha', 'ECoR', 0],
  ['BBS', 'BHUBANESWAR', 'Bhubaneswar', 'Odisha', 'ECoR', 1],
  ['CTC', 'CUTTACK JN', 'Cuttack', 'Odisha', 'ECoR', 1],
  ['PURI', 'PURI', 'Puri', 'Odisha', 'ECoR', 1],
  ['KUR', 'KHURDA ROAD JN', 'Khurda', 'Odisha', 'ECoR', 1],
  ['BAM', 'BRAHMAPUR', 'Berhampur', 'Odisha', 'ECoR', 0],
  ['BHC', 'BHADRAK', 'Bhadrak', 'Odisha', 'ECoR', 0],
  ['BLS', 'BALESHWAR (BALASORE)', 'Balasore', 'Odisha', 'SER', 0],
  ['HWH', 'HOWRAH JN', 'Kolkata', 'West Bengal', 'ER', 1],
  ['SDAH', 'SEALDAH', 'Kolkata', 'West Bengal', 'ER', 1],
  ['KOAA', 'KOLKATA (CHITPUR)', 'Kolkata', 'West Bengal', 'ER', 1],
  ['SHM', 'SHALIMAR', 'Howrah', 'West Bengal', 'SER', 1],
  ['SRC', 'SANTRAGACHI JN', 'Howrah', 'West Bengal', 'SER', 0],
  ['KGP', 'KHARAGPUR JN', 'Kharagpur', 'West Bengal', 'SER', 1],
  ['BWN', 'BARDDHAMAN JN', 'Bardhaman', 'West Bengal', 'ER', 1],
  ['DGR', 'DURGAPUR', 'Durgapur', 'West Bengal', 'ER', 1],
  ['ASN', 'ASANSOL JN', 'Asansol', 'West Bengal', 'ER', 1],
  ['RPH', 'RAMPURHAT JN', 'Birbhum', 'West Bengal', 'ER', 0],
  ['BHP', 'BOLPUR SHANTINIKETAN', 'Birbhum', 'West Bengal', 'ER', 1],
  ['MLDT', 'MALDA TOWN', 'Malda', 'West Bengal', 'ER', 1],
  ['NFK', 'NEW FARAKKA JN', 'Murshidabad', 'West Bengal', 'ER', 0],
  ['NJP', 'NEW JALPAIGURI (SILIGURI)', 'Siliguri', 'West Bengal', 'NFR', 1],
  ['SGUJ', 'SILIGURI JN', 'Siliguri', 'West Bengal', 'NFR', 0],
  ['APDJ', 'ALIPUR DUAR JN', 'Alipurduar', 'West Bengal', 'NFR', 0],
  ['NOQ', 'NEW ALIPURDUAR', 'Alipurduar', 'West Bengal', 'NFR', 0],
  ['NCB', 'NEW COOCH BEHAR', 'Cooch Behar', 'West Bengal', 'NFR', 0],
  ['NBQ', 'NEW BONGAIGAON JN', 'Bongaigaon', 'Assam', 'NFR', 1],
  ['GHY', 'GUWAHATI', 'Guwahati', 'Assam', 'NFR', 1],
  ['KYQ', 'KAMAKHYA JN', 'Guwahati', 'Assam', 'NFR', 1],
  ['LMG', 'LUMDING JN', 'Hojai', 'Assam', 'NFR', 0],
  ['DBRG', 'DIBRUGARH', 'Dibrugarh', 'Assam', 'NFR', 1],
  ['TSK', 'TINSUKIA JN', 'Tinsukia', 'Assam', 'NFR', 0],
  ['NTSK', 'NEW TINSUKIA JN', 'Tinsukia', 'Assam', 'NFR', 0],
  ['DMV', 'DIMAPUR', 'Dimapur', 'Nagaland', 'NFR', 1],
  ['AGTL', 'AGARTALA', 'Agartala', 'Tripura', 'NFR', 1],
  ['SCL', 'SILCHAR', 'Cachar', 'Assam', 'NFR', 0],
  ['MAS', 'CHENNAI CENTRAL (MGR CHENNAI)', 'Chennai', 'Tamil Nadu', 'SR', 1],
  ['MS', 'CHENNAI EGMORE', 'Chennai', 'Tamil Nadu', 'SR', 1],
  ['TBM', 'TAMBARAM', 'Chennai', 'Tamil Nadu', 'SR', 1],
  ['AJJ', 'ARAKKONAM JN', 'Arakkonam', 'Tamil Nadu', 'SR', 0],
  ['KPD', 'KATPADI JN (VELLORE)', 'Vellore', 'Tamil Nadu', 'SR', 1],
  ['JTJ', 'JOLARPETTAI JN', 'Tirupattur', 'Tamil Nadu', 'SR', 0],
  ['SA', 'SALEM JN', 'Salem', 'Tamil Nadu', 'SR', 1],
  ['ED', 'ERODE JN', 'Erode', 'Tamil Nadu', 'SR', 1],
  ['TUP', 'TIRUPPUR', 'Tiruppur', 'Tamil Nadu', 'SR', 0],
  ['CBE', 'COIMBATORE JN', 'Coimbatore', 'Tamil Nadu', 'SR', 1],
  ['TPJ', 'TIRUCHCHIRAPPALLI JN (TRICHY)', 'Tiruchirappalli', 'Tamil Nadu', 'SR', 1],
  ['MDU', 'MADURAI JN', 'Madurai', 'Tamil Nadu', 'SR', 1],
  ['DG', 'DINDIGUL JN', 'Dindigul', 'Tamil Nadu', 'SR', 0],
  ['TEN', 'TIRUNELVELI JN', 'Tirunelveli', 'Tamil Nadu', 'SR', 1],
  ['CAPE', 'KANYAKUMARI', 'Kanyakumari', 'Tamil Nadu', 'SR', 1],
  ['NCJ', 'NAGERCOIL JN', 'Nagercoil', 'Tamil Nadu', 'SR', 1],
  ['RMM', 'RAMESWARAM', 'Rameswaram', 'Tamil Nadu', 'SR', 1],
  ['MV', 'MAYILADUTURAI JN', 'Mayiladuthurai', 'Tamil Nadu', 'SR', 0],
  ['TVR', 'THIRUVARUR JN', 'Thiruvarur', 'Tamil Nadu', 'SR', 0],
  ['TJ', 'THANJAVUR JN', 'Thanjavur', 'Tamil Nadu', 'SR', 0],
  ['VM', 'VILLUPURAM JN', 'Villupuram', 'Tamil Nadu', 'SR', 1],
  ['CUD', 'TIRUPADRIPULYUR (CUDDALORE)', 'Cuddalore', 'Tamil Nadu', 'SR', 0],
  ['PDY', 'PUDUCHERRY', 'Puducherry', 'Puducherry', 'SR', 1],
  ['TVC', 'THIRUVANANTHAPURAM CENTRAL', 'Thiruvananthapuram', 'Kerala', 'SR', 1],
  ['KCVL', 'KOCHUVELI', 'Thiruvananthapuram', 'Kerala', 'SR', 1],
  ['QLN', 'KOLLAM JN (QUILON)', 'Kollam', 'Kerala', 'SR', 1],
  ['KYJ', 'KAYANKULAM JN', 'Alappuzha', 'Kerala', 'SR', 0],
  ['ALLP', 'ALAPPUZHA (ALLEPPEY)', 'Alappuzha', 'Kerala', 'SR', 1],
  ['CNGR', 'CHENGANNUR (SABARIMALA)', 'Alappuzha', 'Kerala', 'SR', 1],
  ['TRVL', 'TIRUVALLA', 'Pathanamthitta', 'Kerala', 'SR', 0],
  ['KTYM', 'KOTTAYAM', 'Kottayam', 'Kerala', 'SR', 1],
  ['ERN', 'ERNAKULAM TOWN (NORTH)', 'Kochi', 'Kerala', 'SR', 1],
  ['ERS', 'ERNAKULAM JN (SOUTH)', 'Kochi', 'Kerala', 'SR', 1],
  ['AWY', 'ALUVA (ALWAYE)', 'Kochi', 'Kerala', 'SR', 0],
  ['TCR', 'THRISUR', 'Thrissur', 'Kerala', 'SR', 1],
  ['SRR', 'SHORANUR JN', 'Palakkad', 'Kerala', 'SR', 1],
  ['PGT', 'PALAKKAD JN (PALGHAT)', 'Palakkad', 'Kerala', 'SR', 1],
  ['TIR', 'TIRUR', 'Malappuram', 'Kerala', 'SR', 0],
  ['CLT', 'KOZHIKODE (CALICUT)', 'Kozhikode', 'Kerala', 'SR', 1],
  ['BDJ', 'VADAKARA', 'Kozhikode', 'Kerala', 'SR', 0],
  ['TLY', 'THALASSERY', 'Kannur', 'Kerala', 'SR', 0],
  ['CAN', 'KANNUR (CANNANORE)', 'Kannur', 'Kerala', 'SR', 1],
  ['KGQ', 'KASARAGOD', 'Kasaragod', 'Kerala', 'SR', 0],
  ['MAQ', 'MANGALURU CENTRAL', 'Mangaluru', 'Karnataka', 'SR', 1],
  ['MAJN', 'MANGALURU JN', 'Mangaluru', 'Karnataka', 'SR', 1],
  ['SBC', 'KSR BENGALURU (BANGALORE CITY)', 'Bengaluru', 'Karnataka', 'SWR', 1],
  ['YPR', 'YESVANTPUR JN', 'Bengaluru', 'Karnataka', 'SWR', 1],
  ['SMVB', 'SMVT BENGALURU (SIR M VISVESVARAYA TERMINAL)', 'Bengaluru', 'Karnataka', 'SWR', 1],
  ['BNC', 'BENGALURU CANTT', 'Bengaluru', 'Karnataka', 'SWR', 0],
  ['KJM', 'KRISHNARAJAPURAM', 'Bengaluru', 'Karnataka', 'SWR', 0],
  ['WFD', 'WHITEFIELD', 'Bengaluru', 'Karnataka', 'SWR', 0],
  ['BWT', 'BANGARAPET JN', 'Kolar', 'Karnataka', 'SWR', 0],
  ['MYS', 'MYSURU JN (MYSORE)', 'Mysuru', 'Karnataka', 'SWR', 1],
  ['HAS', 'HASSAN JN', 'Hassan', 'Karnataka', 'SWR', 0],
  ['TK', 'TUMAKURU (TUMKUR)', 'Tumakuru', 'Karnataka', 'SWR', 0],
  ['ASK', 'ARSIKERE JN', 'Hassan', 'Karnataka', 'SWR', 0],
  ['DVG', 'DAVANGERE', 'Davanagere', 'Karnataka', 'SWR', 0],
  ['UBL', 'SSS HUBBALLI JN (HUBLI)', 'Hubballi', 'Karnataka', 'SWR', 1],
  ['DWR', 'DHARWAD', 'Dharwad', 'Karnataka', 'SWR', 0],
  ['BGM', 'BELAGAVI (BELGAUM)', 'Belagavi', 'Karnataka', 'SWR', 1],
  ['BJP', 'VIJAYAPURA (BIJAPUR)', 'Vijayapura', 'Karnataka', 'SWR', 0],
  ['BGK', 'BAGALKOT', 'Bagalkot', 'Karnataka', 'SWR', 0],
  ['GDG', 'GADAG JN', 'Gadag', 'Karnataka', 'SWR', 0],
  ['KBL', 'KOPPAL', 'Koppal', 'Karnataka', 'SWR', 0],
  ['HPT', 'HOSAPETE JN (HAMPI)', 'Ballari', 'Karnataka', 'SWR', 1],
  ['BAY', 'BALLARI JN (BELLARY)', 'Ballari', 'Karnataka', 'SWR', 0],
  ['RC', 'RAICHUR JN', 'Raichur', 'Karnataka', 'SCR', 0],
  ['YG', 'YADGIR', 'Yadgir', 'Karnataka', 'SCR', 0],
  ['WADI', 'WADI JN', 'Kalaburagi', 'Karnataka', 'CR', 1],
  ['KLBG', 'KALABURAGI (GULBARGA)', 'Kalaburagi', 'Karnataka', 'CR', 1],
  ['BIDR', 'BIDAR', 'Bidar', 'Karnataka', 'SCR', 0],
  ['SC', 'SECUNDERABAD JN', 'Hyderabad', 'Telangana', 'SCR', 1],
  ['HYB', 'HYDERABAD DECCAN (NAM PALLY)', 'Hyderabad', 'Telangana', 'SCR', 1],
  ['KCG', 'KACHEGUDA', 'Hyderabad', 'Telangana', 'SCR', 1],
  ['LPI', 'LINGAMPALLI', 'Hyderabad', 'Telangana', 'SCR', 0],
  ['CHZ', 'CHARLAPALLI', 'Hyderabad', 'Telangana', 'SCR', 0],
  ['KZJ', 'KAZIPET JN', 'Warangal', 'Telangana', 'SCR', 1],
  ['WL', 'WARANGAL', 'Warangal', 'Telangana', 'SCR', 1],
  ['KMT', 'KHAMMAM', 'Khammam', 'Telangana', 'SCR', 0],
  ['MCI', 'MANCHIRYAL', 'Mancherial', 'Telangana', 'SCR', 0],
  ['RDM', 'RAMAGUNDAM', 'Peddapalli', 'Telangana', 'SCR', 0],
  ['NZB', 'NIZAMABAD JN', 'Nizamabad', 'Telangana', 'SCR', 0],
  ['MBNR', 'MAHBUBNAGAR', 'Mahabubnagar', 'Telangana', 'SCR', 0],
  ['BZA', 'VIJAYAWADA JN', 'Vijayawada', 'Andhra Pradesh', 'SCR', 1],
  ['GNT', 'GUNTUR JN', 'Guntur', 'Andhra Pradesh', 'SCR', 1],
  ['TEL', 'TENALI JN', 'Tenali', 'Andhra Pradesh', 'SCR', 0],
  ['OGL', 'ONGOLE', 'Ongole', 'Andhra Pradesh', 'SCR', 0],
  ['NLR', 'NELLORE', 'Nellore', 'Andhra Pradesh', 'SCR', 1],
  ['GDR', 'GUDUR JN', 'Nellore', 'Andhra Pradesh', 'SCR', 0],
  ['RU', 'RENIGUNTA JN', 'Tirupati', 'Andhra Pradesh', 'SCR', 1],
  ['TPTY', 'TIRUPATI MAIN', 'Tirupati', 'Andhra Pradesh', 'SCR', 1],
  ['KDP', 'KADAPA (CUDDAPAH)', 'Kadapa', 'Andhra Pradesh', 'SCR', 0],
  ['YA', 'YERRAGUNTLA JN', 'Kadapa', 'Andhra Pradesh', 'SCR', 0],
  ['DHNE', 'DHONE JN', 'Nandyal', 'Andhra Pradesh', 'SCR', 0],
  ['KRNT', 'KURNOOL CITY', 'Kurnool', 'Andhra Pradesh', 'SCR', 1],
  ['GTL', 'GUNTAKAL JN', 'Anantapur', 'Andhra Pradesh', 'SCR', 1],
  ['ATP', 'ANANTAPUR', 'Anantapur', 'Andhra Pradesh', 'SCR', 0],
  ['EE', 'ELURU', 'Eluru', 'Andhra Pradesh', 'SCR', 0],
  ['TDD', 'TADEPALLIGUDEM', 'West Godavari', 'Andhra Pradesh', 'SCR', 0],
  ['RJY', 'RAJAHMUNDRY', 'Rajahmundry', 'Andhra Pradesh', 'SCR', 1],
  ['SLO', 'SAMALKOT JN (KAKINADA)', 'Kakinada', 'Andhra Pradesh', 'SCR', 0],
  ['CCT', 'KAKINADA TOWN', 'Kakinada', 'Andhra Pradesh', 'SCR', 0],
  ['COA', 'KAKINADA PORT', 'Kakinada', 'Andhra Pradesh', 'SCR', 0],
  ['ANV', 'ANNAVARAM', 'Kakinada', 'Andhra Pradesh', 'SCR', 0],
  ['TUNI', 'TUNI', 'Kakinada', 'Andhra Pradesh', 'SCR', 0],
  ['AKP', 'ANAKAPALLE', 'Visakhapatnam', 'Andhra Pradesh', 'SCR', 0],
  ['DVD', 'DUVVADA', 'Visakhapatnam', 'Andhra Pradesh', 'ECoR', 0],
  ['VSKP', 'VISAKHAPATNAM JN', 'Visakhapatnam', 'Andhra Pradesh', 'ECoR', 1],
  ['VZM', 'VIZIANAGARAM JN', 'Vizianagaram', 'Andhra Pradesh', 'ECoR', 0],
  ['CHE', 'SRIKAKULAM ROAD', 'Srikakulam', 'Andhra Pradesh', 'ECoR', 0],
];

export const ALL_INDIAN_STATIONS: StationModel[] = RAW_STATIONS.map(
  ([code, name, city, state, zone, isPopular]) => ({
    code,
    name,
    city,
    state,
    zone,
    isPopular: isPopular === 1,
  })
);
