export interface StationModel {
  code: string;
  name: string;
  city: string;
  state: string;
  zone: string;
  isPopular: boolean;
  keywords?: string[];
}

export const generateStationKeywords = (station: StationModel): string[] => {
  const set = new Set<string>();
  const addVariations = (text?: string) => {
    if (!text) return;
    const clean = text.toLowerCase().trim();
    set.add(clean);
    // Prefixes from 2 characters upwards
    for (let i = 2; i <= clean.length; i++) {
      set.add(clean.slice(0, i));
    }
    // Individual words and their prefixes
    const words = clean.split(/[\s\-()\/,]+/);
    for (const w of words) {
      if (w.length >= 2) {
        set.add(w);
        for (let i = 2; i <= w.length; i++) {
          set.add(w.slice(0, i));
        }
      }
    }
  };

  addVariations(station.code);
  addVariations(station.name);
  addVariations(station.city);
  addVariations(station.state);

  return Array.from(set).slice(0, 100);
};

export const ALL_INDIAN_STATIONS: StationModel[] = [
  // ─── NORTHERN ZONE (NR & NCR) ──────────────────────────────
  { code: 'NDLS', name: 'NEW DELHI', city: 'New Delhi', state: 'Delhi', zone: 'NR', isPopular: true },
  { code: 'NZM', name: 'HAZRAT NIZAMUDDIN JN', city: 'New Delhi', state: 'Delhi', zone: 'NR', isPopular: true },
  { code: 'DLI', name: 'OLD DELHI JN', city: 'Delhi', state: 'Delhi', zone: 'NR', isPopular: true },
  { code: 'ANVT', name: 'ANAND VIHAR TERMINAL', city: 'Delhi', state: 'Delhi', zone: 'NR', isPopular: true },
  { code: 'DEC', name: 'DELHI CANTT', city: 'Delhi', state: 'Delhi', zone: 'NR', isPopular: true },
  { code: 'DEE', name: 'DELHI SARAI ROHILLA', city: 'Delhi', state: 'Delhi', zone: 'NR', isPopular: true },
  { code: 'MRA', name: 'MORENA', city: 'Morena', state: 'Madhya Pradesh', zone: 'NCR', isPopular: true },
  { code: 'GWL', name: 'GWALIOR JN', city: 'Gwalior', state: 'Madhya Pradesh', zone: 'NCR', isPopular: true },
  { code: 'DBA', name: 'DABRA', city: 'Dabra', state: 'Madhya Pradesh', zone: 'NCR', isPopular: false },
  { code: 'AGC', name: 'AGRA CANTT', city: 'Agra', state: 'Uttar Pradesh', zone: 'NCR', isPopular: true },
  { code: 'AF', name: 'AGRA FORT', city: 'Agra', state: 'Uttar Pradesh', zone: 'NCR', isPopular: true },
  { code: 'RKM', name: 'RAJA KI MANDI', city: 'Agra', state: 'Uttar Pradesh', zone: 'NCR', isPopular: true },
  { code: 'MTJ', name: 'MATHURA JN', city: 'Mathura', state: 'Uttar Pradesh', zone: 'NCR', isPopular: true },
  { code: 'VRBD', name: 'VRINDAVAN', city: 'Mathura', state: 'Uttar Pradesh', zone: 'NCR', isPopular: false },
  { code: 'ALJN', name: 'ALIGARH JN', city: 'Aligarh', state: 'Uttar Pradesh', zone: 'NCR', isPopular: true },
  { code: 'TDL', name: 'TUNDLA JN', city: 'Firozabad', state: 'Uttar Pradesh', zone: 'NCR', isPopular: true },
  { code: 'ETW', name: 'ETAWAH JN', city: 'Etawah', state: 'Uttar Pradesh', zone: 'NCR', isPopular: true },
  { code: 'CNB', name: 'KANPUR CENTRAL', city: 'Kanpur', state: 'Uttar Pradesh', zone: 'NCR', isPopular: true },
  { code: 'CPA', name: 'KANPUR ANWRGANJ', city: 'Kanpur', state: 'Uttar Pradesh', zone: 'NER', isPopular: false },
  { code: 'LKO', name: 'LUCKNOW CHARBAGH', city: 'Lucknow', state: 'Uttar Pradesh', zone: 'NR', isPopular: true },
  { code: 'LJN', name: 'LUCKNOW JN NER', city: 'Lucknow', state: 'Uttar Pradesh', zone: 'NER', isPopular: true },
  { code: 'BNZ', name: 'BADSHAHNAGAR', city: 'Lucknow', state: 'Uttar Pradesh', zone: 'NER', isPopular: false },
  { code: 'PRYJ', name: 'PRAYAGRAJ JN (ALLAHABAD)', city: 'Prayagraj', state: 'Uttar Pradesh', zone: 'NCR', isPopular: true },
  { code: 'PRRB', name: 'PRAYAGRAJ RAMBAG', city: 'Prayagraj', state: 'Uttar Pradesh', zone: 'NER', isPopular: false },
  { code: 'BSB', name: 'VARANASI JN', city: 'Varanasi', state: 'Uttar Pradesh', zone: 'NR', isPopular: true },
  { code: 'BSBS', name: 'BANARAS (MANDUADIH)', city: 'Varanasi', state: 'Uttar Pradesh', zone: 'NER', isPopular: true },
  { code: 'DDU', name: 'PT DEEN DAYAL UPADHYAYA JN (MUGHALSARAI)', city: 'Chandauli', state: 'Uttar Pradesh', zone: 'ECR', isPopular: true },
  { code: 'GKP', name: 'GORAKHPUR JN', city: 'Gorakhpur', state: 'Uttar Pradesh', zone: 'NER', isPopular: true },
  { code: 'BE', name: 'BAREILLY JN', city: 'Bareilly', state: 'Uttar Pradesh', zone: 'NR', isPopular: true },
  { code: 'MB', name: 'MORADABAD JN', city: 'Moradabad', state: 'Uttar Pradesh', zone: 'NR', isPopular: true },
  { code: 'MTC', name: 'MEERUT CITY JN', city: 'Meerut', state: 'Uttar Pradesh', zone: 'NR', isPopular: true },
  { code: 'GZB', name: 'GHAZIABAD JN', city: 'Ghaziabad', state: 'Uttar Pradesh', zone: 'NR', isPopular: true },
  { code: 'SRE', name: 'SAHARANPUR JN', city: 'Saharanpur', state: 'Uttar Pradesh', zone: 'NR', isPopular: true },
  { code: 'JHS', name: 'VIRANGANA LAKSHMIBAI (JHANSI)', city: 'Jhansi', state: 'Uttar Pradesh', zone: 'NCR', isPopular: true },
  { code: 'LIT', name: 'LALITPUR JN', city: 'Lalitpur', state: 'Uttar Pradesh', zone: 'NCR', isPopular: false },
  { code: 'BNDA', name: 'BANDA JN', city: 'Banda', state: 'Uttar Pradesh', zone: 'NCR', isPopular: false },
  { code: 'MKP', name: 'MANIKPUR JN', city: 'Chitrakoot', state: 'Uttar Pradesh', zone: 'NCR', isPopular: false },
  { code: 'AY', name: 'AYODHYA DHAM JN', city: 'Ayodhya', state: 'Uttar Pradesh', zone: 'NR', isPopular: true },
  { code: 'AYC', name: 'AYODHYA CANTT', city: 'Ayodhya', state: 'Uttar Pradesh', zone: 'NR', isPopular: true },
  { code: 'FD', name: 'FAIZABAD JN', city: 'Ayodhya', state: 'Uttar Pradesh', zone: 'NR', isPopular: false },
  { code: 'SLN', name: 'SULTANPUR JN', city: 'Sultanpur', state: 'Uttar Pradesh', zone: 'NR', isPopular: false },
  { code: 'JNU', name: 'JAUNPUR JN', city: 'Jaunpur', state: 'Uttar Pradesh', zone: 'NR', isPopular: false },
  { code: 'MAU', name: 'MAU JN', city: 'Mau', state: 'Uttar Pradesh', zone: 'NER', isPopular: false },
  { code: 'BUI', name: 'BALLIA', city: 'Ballia', state: 'Uttar Pradesh', zone: 'NER', isPopular: false },
  { code: 'GD', name: 'GONDA JN', city: 'Gonda', state: 'Uttar Pradesh', zone: 'NER', isPopular: false },
  { code: 'BST', name: 'BASTI', city: 'Basti', state: 'Uttar Pradesh', zone: 'NER', isPopular: false },
  { code: 'KLD', name: 'KHALILABAD', city: 'Sant Kabir Nagar', state: 'Uttar Pradesh', zone: 'NER', isPopular: false },
  { code: 'DEOS', name: 'DEORIA SADAR', city: 'Deoria', state: 'Uttar Pradesh', zone: 'NER', isPopular: false },
  { code: 'STP', name: 'SITAPUR JN', city: 'Sitapur', state: 'Uttar Pradesh', zone: 'NER', isPopular: false },
  { code: 'SPN', name: 'SHAHJAHANPUR', city: 'Shahjahanpur', state: 'Uttar Pradesh', zone: 'NR', isPopular: false },
  { code: 'HRI', name: 'HARDOI', city: 'Hardoi', state: 'Uttar Pradesh', zone: 'NR', isPopular: false },
  { code: 'CH', name: 'CHANDAUSI JN', city: 'Sambhal', state: 'Uttar Pradesh', zone: 'NR', isPopular: false },
  { code: 'HW', name: 'HARIDWAR JN', city: 'Haridwar', state: 'Uttarakhand', zone: 'NR', isPopular: true },
  { code: 'DDN', name: 'DEHRADUN', city: 'Dehradun', state: 'Uttarakhand', zone: 'NR', isPopular: true },
  { code: 'RK', name: 'ROORKEE', city: 'Roorkee', state: 'Uttarakhand', zone: 'NR', isPopular: true },
  { code: 'KGM', name: 'KATHGODAM', city: 'Kathgodam', state: 'Uttarakhand', zone: 'NER', isPopular: true },
  { code: 'LKU', name: 'LALKUAN JN', city: 'Nainital', state: 'Uttarakhand', zone: 'NER', isPopular: false },
  { code: 'KLK', name: 'KALKA', city: 'Panchkula', state: 'Haryana', zone: 'NR', isPopular: true },
  { code: 'CDG', name: 'CHANDIGARH JN', city: 'Chandigarh', state: 'Chandigarh', zone: 'NR', isPopular: true },
  { code: 'UMB', name: 'AMBALA CANTT JN', city: 'Ambala', state: 'Haryana', zone: 'NR', isPopular: true },
  { code: 'PNP', name: 'PANIPAT JN', city: 'Panipat', state: 'Haryana', zone: 'NR', isPopular: true },
  { code: 'KUN', name: 'KARNAL', city: 'Karnal', state: 'Haryana', zone: 'NR', isPopular: false },
  { code: 'KKDE', name: 'KURUKSHETRA JN', city: 'Kurukshetra', state: 'Haryana', zone: 'NR', isPopular: false },
  { code: 'ROK', name: 'ROHTAK JN', city: 'Rohtak', state: 'Haryana', zone: 'NR', isPopular: false },
  { code: 'HSR', name: 'HISAR JN', city: 'Hisar', state: 'Haryana', zone: 'NWR', isPopular: false },
  { code: 'BNW', name: 'BHIWANI JN', city: 'Bhiwani', state: 'Haryana', zone: 'NWR', isPopular: false },
  { code: 'RE', name: 'REWARI JN', city: 'Rewari', state: 'Haryana', zone: 'NWR', isPopular: true },
  { code: 'LDH', name: 'LUDHIANA JN', city: 'Ludhiana', state: 'Punjab', zone: 'NR', isPopular: true },
  { code: 'JUC', name: 'JALANDHAR CITY JN', city: 'Jalandhar', state: 'Punjab', zone: 'NR', isPopular: true },
  { code: 'JRC', name: 'JALANDHAR CANTT', city: 'Jalandhar', state: 'Punjab', zone: 'NR', isPopular: false },
  { code: 'ASR', name: 'AMRITSAR JN', city: 'Amritsar', state: 'Punjab', zone: 'NR', isPopular: true },
  { code: 'BTI', name: 'BHATINDA JN', city: 'Bathinda', state: 'Punjab', zone: 'NR', isPopular: true },
  { code: 'PTA', name: 'PATIALA', city: 'Patiala', state: 'Punjab', zone: 'NR', isPopular: false },
  { code: 'PGW', name: 'PHAGWARA JN', city: 'Phagwara', state: 'Punjab', zone: 'NR', isPopular: false },
  { code: 'BEAS', name: 'BEAS JN', city: 'Beas', state: 'Punjab', zone: 'NR', isPopular: false },
  { code: 'PTKC', name: 'PATHANKOT CANTT', city: 'Pathankot', state: 'Punjab', zone: 'NR', isPopular: true },
  { code: 'JAT', name: 'JAMMU TAWI', city: 'Jammu', state: 'Jammu & Kashmir', zone: 'NR', isPopular: true },
  { code: 'UHP', name: 'UDHAMPUR', city: 'Udhampur', state: 'Jammu & Kashmir', zone: 'NR', isPopular: false },
  { code: 'SVDK', name: 'SMVD KATRA (VAISHNO DEVI)', city: 'Katra', state: 'Jammu & Kashmir', zone: 'NR', isPopular: true },

  // ─── WESTERN & CENTRAL ZONE (WR & CR) ───────────────────────
  { code: 'CSTM', name: 'MUMBAI CSMT', city: 'Mumbai', state: 'Maharashtra', zone: 'CR', isPopular: true },
  { code: 'MMCT', name: 'MUMBAI CENTRAL', city: 'Mumbai', state: 'Maharashtra', zone: 'WR', isPopular: true },
  { code: 'BDTS', name: 'BANDRA TERMINUS', city: 'Mumbai', state: 'Maharashtra', zone: 'WR', isPopular: true },
  { code: 'LTT', name: 'LOKMANYA TILAK TERMINUS (KURLA)', city: 'Mumbai', state: 'Maharashtra', zone: 'CR', isPopular: true },
  { code: 'DR', name: 'DADAR CR', city: 'Mumbai', state: 'Maharashtra', zone: 'CR', isPopular: true },
  { code: 'DDR', name: 'DADAR WR', city: 'Mumbai', state: 'Maharashtra', zone: 'WR', isPopular: true },
  { code: 'TNA', name: 'THANE', city: 'Thane', state: 'Maharashtra', zone: 'CR', isPopular: true },
  { code: 'KYN', name: 'KALYAN JN', city: 'Kalyan', state: 'Maharashtra', zone: 'CR', isPopular: true },
  { code: 'BSR', name: 'VASAI ROAD', city: 'Vasai', state: 'Maharashtra', zone: 'WR', isPopular: true },
  { code: 'PNVL', name: 'PANVEL JN', city: 'Navi Mumbai', state: 'Maharashtra', zone: 'CR', isPopular: true },
  { code: 'PUNE', name: 'PUNE JN', city: 'Pune', state: 'Maharashtra', zone: 'CR', isPopular: true },
  { code: 'LNL', name: 'LONAVALA', city: 'Lonavala', state: 'Maharashtra', zone: 'CR', isPopular: true },
  { code: 'DD', name: 'DAUND JN', city: 'Daund', state: 'Maharashtra', zone: 'CR', isPopular: false },
  { code: 'SUR', name: 'SOLAPUR JN', city: 'Solapur', state: 'Maharashtra', zone: 'CR', isPopular: true },
  { code: 'KOP', name: 'KOLHAPUR SCSMT', city: 'Kolhapur', state: 'Maharashtra', zone: 'CR', isPopular: true },
  { code: 'MRJ', name: 'MIRAJ JN', city: 'Miraj', state: 'Maharashtra', zone: 'CR', isPopular: false },
  { code: 'STR', name: 'SATARA', city: 'Satara', state: 'Maharashtra', zone: 'CR', isPopular: false },
  { code: 'NK', name: 'NASHIK ROAD', city: 'Nashik', state: 'Maharashtra', zone: 'CR', isPopular: true },
  { code: 'MMR', name: 'MANMAD JN', city: 'Manmad', state: 'Maharashtra', zone: 'CR', isPopular: true },
  { code: 'BSL', name: 'BHUSAVAL JN', city: 'Bhusawal', state: 'Maharashtra', zone: 'CR', isPopular: true },
  { code: 'JL', name: 'JALGAON JN', city: 'Jalgaon', state: 'Maharashtra', zone: 'CR', isPopular: true },
  { code: 'CSN', name: 'CHALISGAON JN', city: 'Chalisgaon', state: 'Maharashtra', zone: 'CR', isPopular: false },
  { code: 'NGP', name: 'NAGPUR JN', city: 'Nagpur', state: 'Maharashtra', zone: 'CR', isPopular: true },
  { code: 'WR', name: 'WARDHA JN', city: 'Wardha', state: 'Maharashtra', zone: 'CR', isPopular: false },
  { code: 'BD', name: 'BADNERA JN (AMRAVATI)', city: 'Amravati', state: 'Maharashtra', zone: 'CR', isPopular: false },
  { code: 'AK', name: 'AKOLA JN', city: 'Akola', state: 'Maharashtra', zone: 'CR', isPopular: true },
  { code: 'SEG', name: 'SHEGAON', city: 'Shegaon', state: 'Maharashtra', zone: 'CR', isPopular: false },
  { code: 'MKU', name: 'MALKAPUR', city: 'Malkapur', state: 'Maharashtra', zone: 'CR', isPopular: false },
  { code: 'CD', name: 'CHANDRAPUR', city: 'Chandrapur', state: 'Maharashtra', zone: 'CR', isPopular: false },
  { code: 'BPQ', name: 'BALHARSHAH JN', city: 'Balharshah', state: 'Maharashtra', zone: 'CR', isPopular: true },
  { code: 'G', name: 'GONDIA JN', city: 'Gondia', state: 'Maharashtra', zone: 'SECR', isPopular: true },
  { code: 'AWB', name: 'AURANGABAD (CHHATRAPATI SAMBHAJINAGAR)', city: 'Chhatrapati Sambhajinagar', state: 'Maharashtra', zone: 'SCR', isPopular: true },
  { code: 'J', name: 'JALNA', city: 'Jalna', state: 'Maharashtra', zone: 'SCR', isPopular: false },
  { code: 'PBN', name: 'PARBHANI JN', city: 'Parbhani', state: 'Maharashtra', zone: 'SCR', isPopular: false },
  { code: 'NED', name: 'HAZUR SAHIB NANDED', city: 'Nanded', state: 'Maharashtra', zone: 'SCR', isPopular: true },
  { code: 'RN', name: 'RATNAGIRI', city: 'Ratnagiri', state: 'Maharashtra', zone: 'KR', isPopular: true },
  { code: 'MAO', name: 'MADGAON JN (GOA)', city: 'Madgaon', state: 'Goa', zone: 'KR', isPopular: true },
  { code: 'VSG', name: 'VASCO DA GAMA', city: 'Vasco', state: 'Goa', zone: 'SWR', isPopular: true },
  { code: 'KRMI', name: 'KARMALI', city: 'Panaji', state: 'Goa', zone: 'KR', isPopular: false },
  { code: 'THVM', name: 'THIVIM', city: 'Mapusa', state: 'Goa', zone: 'KR', isPopular: false },

  // ─── GUJARAT & RAJASTHAN (WR & NWR) ─────────────────────────
  { code: 'ADI', name: 'AHMEDABAD JN', city: 'Ahmedabad', state: 'Gujarat', zone: 'WR', isPopular: true },
  { code: 'SBT', name: 'SABARMATI JN', city: 'Ahmedabad', state: 'Gujarat', zone: 'WR', isPopular: false },
  { code: 'BRC', name: 'VADODARA JN', city: 'Vadodara', state: 'Gujarat', zone: 'WR', isPopular: true },
  { code: 'ST', name: 'SURAT', city: 'Surat', state: 'Gujarat', zone: 'WR', isPopular: true },
  { code: 'UDN', name: 'UDHNA JN', city: 'Surat', state: 'Gujarat', zone: 'WR', isPopular: false },
  { code: 'BL', name: 'VALSAD', city: 'Valsad', state: 'Gujarat', zone: 'WR', isPopular: false },
  { code: 'VAPI', name: 'VAPI', city: 'Vapi', state: 'Gujarat', zone: 'WR', isPopular: true },
  { code: 'BH', name: 'BHARUCH JN', city: 'Bharuch', state: 'Gujarat', zone: 'WR', isPopular: false },
  { code: 'ANND', name: 'ANAND JN', city: 'Anand', state: 'Gujarat', zone: 'WR', isPopular: true },
  { code: 'ND', name: 'NADIAD JN', city: 'Nadiad', state: 'Gujarat', zone: 'WR', isPopular: false },
  { code: 'RJT', name: 'RAJKOT JN', city: 'Rajkot', state: 'Gujarat', zone: 'WR', isPopular: true },
  { code: 'JAM', name: 'JAMNAGAR', city: 'Jamnagar', state: 'Gujarat', zone: 'WR', isPopular: false },
  { code: 'DWK', name: 'DWARKA', city: 'Dwarka', state: 'Gujarat', zone: 'WR', isPopular: true },
  { code: 'OKHA', name: 'OKHA', city: 'Okha', state: 'Gujarat', zone: 'WR', isPopular: false },
  { code: 'PBR', name: 'PORBANDAR', city: 'Porbandar', state: 'Gujarat', zone: 'WR', isPopular: false },
  { code: 'JND', name: 'JUNAGADH JN', city: 'Junagadh', state: 'Gujarat', zone: 'WR', isPopular: false },
  { code: 'VRL', name: 'VERAVAL JN (SOMNATH)', city: 'Veraval', state: 'Gujarat', zone: 'WR', isPopular: true },
  { code: 'BVC', name: 'BHAVNAGAR TERMINUS', city: 'Bhavnagar', state: 'Gujarat', zone: 'WR', isPopular: false },
  { code: 'GIMB', name: 'GANDHIDHAM JN', city: 'Gandhidham', state: 'Gujarat', zone: 'WR', isPopular: true },
  { code: 'BHUJ', name: 'BHUJ', city: 'Bhuj', state: 'Gujarat', zone: 'WR', isPopular: true },
  { code: 'PNU', name: 'PALANPUR JN', city: 'Palanpur', state: 'Gujarat', zone: 'WR', isPopular: false },
  { code: 'MSH', name: 'MEHSANA JN', city: 'Mehsana', state: 'Gujarat', zone: 'WR', isPopular: false },
  { code: 'JP', name: 'JAIPUR JN', city: 'Jaipur', state: 'Rajasthan', zone: 'NWR', isPopular: true },
  { code: 'GADJ', name: 'GANDHINAGAR JAIPUR', city: 'Jaipur', state: 'Rajasthan', zone: 'NWR', isPopular: false },
  { code: 'DO', name: 'DAUSA', city: 'Dausa', state: 'Rajasthan', zone: 'NWR', isPopular: false },
  { code: 'BKI', name: 'BANDIKUI JN', city: 'Bandikui', state: 'Rajasthan', zone: 'NWR', isPopular: false },
  { code: 'AWR', name: 'ALWAR JN', city: 'Alwar', state: 'Rajasthan', zone: 'NWR', isPopular: true },
  { code: 'AII', name: 'AJMER JN', city: 'Ajmer', state: 'Rajasthan', zone: 'NWR', isPopular: true },
  { code: 'KSG', name: 'KISHANGARH', city: 'Kishangarh', state: 'Rajasthan', zone: 'NWR', isPopular: false },
  { code: 'FL', name: 'PHULERA JN', city: 'Phulera', state: 'Rajasthan', zone: 'NWR', isPopular: false },
  { code: 'JU', name: 'JODHPUR JN', city: 'Jodhpur', state: 'Rajasthan', zone: 'NWR', isPopular: true },
  { code: 'BME', name: 'BARMER', city: 'Barmer', state: 'Rajasthan', zone: 'NWR', isPopular: false },
  { code: 'JSM', name: 'JAISALMER', city: 'Jaisalmer', state: 'Rajasthan', zone: 'NWR', isPopular: true },
  { code: 'BKN', name: 'BIKANER JN', city: 'Bikaner', state: 'Rajasthan', zone: 'NWR', isPopular: true },
  { code: 'LGH', name: 'LALGARH JN', city: 'Bikaner', state: 'Rajasthan', zone: 'NWR', isPopular: false },
  { code: 'SGNR', name: 'SHRI GANGANAGAR', city: 'Sri Ganganagar', state: 'Rajasthan', zone: 'NWR', isPopular: false },
  { code: 'UDZ', name: 'UDAIPUR CITY', city: 'Udaipur', state: 'Rajasthan', zone: 'NWR', isPopular: true },
  { code: 'COR', name: 'CHITTAURGARH JN', city: 'Chittorgarh', state: 'Rajasthan', zone: 'WR', isPopular: true },
  { code: 'BHL', name: 'BHILWARA', city: 'Bhilwara', state: 'Rajasthan', zone: 'NWR', isPopular: false },
  { code: 'KOTA', name: 'KOTA JN', city: 'Kota', state: 'Rajasthan', zone: 'WCR', isPopular: true },
  { code: 'SWM', name: 'SAWAI MADHOPUR JN', city: 'Sawai Madhopur', state: 'Rajasthan', zone: 'WCR', isPopular: true },
  { code: 'GGC', name: 'GANGAPUR CITY', city: 'Gangapur', state: 'Rajasthan', zone: 'WCR', isPopular: false },
  { code: 'HAN', name: 'HINDAUN CITY', city: 'Hindaun', state: 'Rajasthan', zone: 'WCR', isPopular: false },
  { code: 'BTE', name: 'BHARATPUR JN', city: 'Bharatpur', state: 'Rajasthan', zone: 'WCR', isPopular: true },
  { code: 'ABR', name: 'ABU ROAD', city: 'Mount Abu', state: 'Rajasthan', zone: 'NWR', isPopular: true },
  { code: 'FA', name: 'FALNA', city: 'Falna', state: 'Rajasthan', zone: 'NWR', isPopular: false },
  { code: 'MJ', name: 'MARWAR JN', city: 'Marwar', state: 'Rajasthan', zone: 'NWR', isPopular: false },

  // ─── MADHYA PRADESH & CHHATTISGARH (WCR, SECR) ─────────────
  { code: 'BPL', name: 'BHOPAL JN', city: 'Bhopal', state: 'Madhya Pradesh', zone: 'WCR', isPopular: true },
  { code: 'RKMP', name: 'RANI KAMLAPATI (HABIBGANJ)', city: 'Bhopal', state: 'Madhya Pradesh', zone: 'WCR', isPopular: true },
  { code: 'INDB', name: 'INDORE JN BG', city: 'Indore', state: 'Madhya Pradesh', zone: 'WR', isPopular: true },
  { code: 'UJN', name: 'UJJAIN JN', city: 'Ujjain', state: 'Madhya Pradesh', zone: 'WR', isPopular: true },
  { code: 'DWX', name: 'DEWAS JN', city: 'Dewas', state: 'Madhya Pradesh', zone: 'WR', isPopular: false },
  { code: 'RTM', name: 'RATLAM JN', city: 'Ratlam', state: 'Madhya Pradesh', zone: 'WR', isPopular: true },
  { code: 'NMH', name: 'NEEMUCH', city: 'Neemuch', state: 'Madhya Pradesh', zone: 'WR', isPopular: false },
  { code: 'MDS', name: 'MANDASOR', city: 'Mandsaur', state: 'Madhya Pradesh', zone: 'WR', isPopular: false },
  { code: 'NAD', name: 'NAGDA JN', city: 'Nagda', state: 'Madhya Pradesh', zone: 'WR', isPopular: false },
  { code: 'ET', name: 'ITARSI JN', city: 'Itarsi', state: 'Madhya Pradesh', zone: 'WCR', isPopular: true },
  { code: 'HBD', name: 'HOSHANGABAD (NARMADAPURAM)', city: 'Narmadapuram', state: 'Madhya Pradesh', zone: 'WCR', isPopular: false },
  { code: 'HD', name: 'HARDA', city: 'Harda', state: 'Madhya Pradesh', zone: 'WCR', isPopular: false },
  { code: 'KNW', name: 'KHANDWA JN', city: 'Khandwa', state: 'Madhya Pradesh', zone: 'CR', isPopular: true },
  { code: 'BAU', name: 'BURHANPUR', city: 'Burhanpur', state: 'Madhya Pradesh', zone: 'CR', isPopular: false },
  { code: 'BINA', name: 'BINA JN', city: 'Bina', state: 'Madhya Pradesh', zone: 'WCR', isPopular: true },
  { code: 'SGO', name: 'SAUGOR (SAGAR)', city: 'Sagar', state: 'Madhya Pradesh', zone: 'WCR', isPopular: false },
  { code: 'DMO', name: 'DAMOH', city: 'Damoh', state: 'Madhya Pradesh', zone: 'WCR', isPopular: false },
  { code: 'KMZ', name: 'KATNI MURWARA', city: 'Katni', state: 'Madhya Pradesh', zone: 'WCR', isPopular: false },
  { code: 'KTE', name: 'KATNI JN', city: 'Katni', state: 'Madhya Pradesh', zone: 'WCR', isPopular: true },
  { code: 'JBP', name: 'JABALPUR JN', city: 'Jabalpur', state: 'Madhya Pradesh', zone: 'WCR', isPopular: true },
  { code: 'MML', name: 'MADAN MAHAL', city: 'Jabalpur', state: 'Madhya Pradesh', zone: 'WCR', isPopular: false },
  { code: 'MYR', name: 'MAIHAR', city: 'Maihar', state: 'Madhya Pradesh', zone: 'WCR', isPopular: false },
  { code: 'STA', name: 'SATNA JN', city: 'Satna', state: 'Madhya Pradesh', zone: 'WCR', isPopular: true },
  { code: 'REWA', name: 'REWA', city: 'Rewa', state: 'Madhya Pradesh', zone: 'WCR', isPopular: true },
  { code: 'PPI', name: 'PIPARIYA (PACHMARHI)', city: 'Pipariya', state: 'Madhya Pradesh', zone: 'WCR', isPopular: true },
  { code: 'GAR', name: 'GADARWARA', city: 'Gadarwara', state: 'Madhya Pradesh', zone: 'WCR', isPopular: false },
  { code: 'NU', name: 'NARSINGHPUR', city: 'Narsinghpur', state: 'Madhya Pradesh', zone: 'WCR', isPopular: false },
  { code: 'VGLB', name: 'VGL JHANSI JN', city: 'Jhansi', state: 'Uttar Pradesh', zone: 'NCR', isPopular: true },
  { code: 'R', name: 'RAIPUR JN', city: 'Raipur', state: 'Chhattisgarh', zone: 'SECR', isPopular: true },
  { code: 'BPHB', name: 'BHILAI POWER HOUSE', city: 'Bhilai', state: 'Chhattisgarh', zone: 'SECR', isPopular: false },
  { code: 'DURG', name: 'DURG JN', city: 'Durg', state: 'Chhattisgarh', zone: 'SECR', isPopular: true },
  { code: 'RJN', name: 'RAJNANDGAON', city: 'Rajnandgaon', state: 'Chhattisgarh', zone: 'SECR', isPopular: false },
  { code: 'BSP', name: 'BILASPUR JN', city: 'Bilaspur', state: 'Chhattisgarh', zone: 'SECR', isPopular: true },
  { code: 'RIG', name: 'RAIGARH', city: 'Raigarh', state: 'Chhattisgarh', zone: 'SECR', isPopular: false },
  { code: 'CPH', name: 'CHAMPA JN', city: 'Janjgir Champa', state: 'Chhattisgarh', zone: 'SECR', isPopular: false },
  { code: 'KRBA', name: 'KORBA', city: 'Korba', state: 'Chhattisgarh', zone: 'SECR', isPopular: false },
  { code: 'APR', name: 'ANUPPUR JN', city: 'Anuppur', state: 'Madhya Pradesh', zone: 'SECR', isPopular: false },
  { code: 'SDL', name: 'SHAHDOL', city: 'Shahdol', state: 'Madhya Pradesh', zone: 'SECR', isPopular: false },
  { code: 'UMR', name: 'UMARIA', city: 'Umaria', state: 'Madhya Pradesh', zone: 'SECR', isPopular: false },

  // ─── BIHAR & JHARKHAND (ECR, SER) ───────────────────────────
  { code: 'PNBE', name: 'PATNA JN', city: 'Patna', state: 'Bihar', zone: 'ECR', isPopular: true },
  { code: 'PPTA', name: 'PATLIPUTRA JN', city: 'Patna', state: 'Bihar', zone: 'ECR', isPopular: true },
  { code: 'DNR', name: 'DANAPUR', city: 'Patna', state: 'Bihar', zone: 'ECR', isPopular: true },
  { code: 'RJPB', name: 'RAJENDRA NAGAR TERMINAL', city: 'Patna', state: 'Bihar', zone: 'ECR', isPopular: true },
  { code: 'PNC', name: 'PATNA SAHEB', city: 'Patna', state: 'Bihar', zone: 'ECR', isPopular: false },
  { code: 'GAYA', name: 'GAYA JN', city: 'Gaya', state: 'Bihar', zone: 'ECR', isPopular: true },
  { code: 'MGS', name: 'MUGHALSARAI (DDU)', city: 'Chandauli', state: 'Uttar Pradesh', zone: 'ECR', isPopular: true },
  { code: 'BXR', name: 'BUXAR', city: 'Buxar', state: 'Bihar', zone: 'ECR', isPopular: false },
  { code: 'ARA', name: 'ARA JN', city: 'Bhojpur', state: 'Bihar', zone: 'ECR', isPopular: true },
  { code: 'MFP', name: 'MUZAFFARPUR JN', city: 'Muzaffarpur', state: 'Bihar', zone: 'ECR', isPopular: true },
  { code: 'HJP', name: 'HAJIPUR JN', city: 'Hajipur', state: 'Bihar', zone: 'ECR', isPopular: true },
  { code: 'SEE', name: 'SONPUR JN', city: 'Sonpur', state: 'Bihar', zone: 'ECR', isPopular: false },
  { code: 'CPR', name: 'CHHAPRA JN', city: 'Chhapra', state: 'Bihar', zone: 'NER', isPopular: true },
  { code: 'SV', name: 'SIWAN JN', city: 'Siwan', state: 'Bihar', zone: 'NER', isPopular: false },
  { code: 'SPJ', name: 'SAMASTIPUR JN', city: 'Samastipur', state: 'Bihar', zone: 'ECR', isPopular: true },
  { code: 'DBG', name: 'DARBHANGA JN', city: 'Darbhanga', state: 'Bihar', zone: 'ECR', isPopular: true },
  { code: 'JYG', name: 'JAYNAGAR', city: 'Madhubani', state: 'Bihar', zone: 'ECR', isPopular: false },
  { code: 'RXL', name: 'RAXAUL JN', city: 'East Champaran', state: 'Bihar', zone: 'ECR', isPopular: false },
  { code: 'BGU', name: 'BAIRGANIA', city: 'Sitamarhi', state: 'Bihar', zone: 'ECR', isPopular: false },
  { code: 'SMI', name: 'SITAMARHI JN', city: 'Sitamarhi', state: 'Bihar', zone: 'ECR', isPopular: false },
  { code: 'BGS', name: 'BEGUSARAI', city: 'Begusarai', state: 'Bihar', zone: 'ECR', isPopular: false },
  { code: 'BJU', name: 'BARAUNI JN', city: 'Barauni', state: 'Bihar', zone: 'ECR', isPopular: true },
  { code: 'KGG', name: 'KHAGARIA JN', city: 'Khagaria', state: 'Bihar', zone: 'ECR', isPopular: false },
  { code: 'MNE', name: 'MANSI JN', city: 'Khagaria', state: 'Bihar', zone: 'ECR', isPopular: false },
  { code: 'NNA', name: 'NAUGACHIA', city: 'Bhagalpur', state: 'Bihar', zone: 'ECR', isPopular: false },
  { code: 'KIR', name: 'KATIHAR JN', city: 'Katihar', state: 'Bihar', zone: 'NFR', isPopular: true },
  { code: 'BGP', name: 'BHAGALPUR JN', city: 'Bhagalpur', state: 'Bihar', zone: 'ER', isPopular: true },
  { code: 'JMP', name: 'JAMALPUR JN', city: 'Munger', state: 'Bihar', zone: 'ER', isPopular: false },
  { code: 'KIUL', name: 'KIUL JN', city: 'Lakhisarai', state: 'Bihar', zone: 'ECR', isPopular: false },
  { code: 'MKA', name: 'MOKAMA JN', city: 'Mokama', state: 'Bihar', zone: 'ECR', isPopular: false },
  { code: 'JAJ', name: 'JHAJHA', city: 'Jamui', state: 'Bihar', zone: 'ECR', isPopular: false },
  { code: 'JSME', name: 'JASIDIH JN (DEOGHAR)', city: 'Deoghar', state: 'Jharkhand', zone: 'ER', isPopular: true },
  { code: 'MDP', name: 'MADHUPUR JN', city: 'Deoghar', state: 'Jharkhand', zone: 'ER', isPopular: false },
  { code: 'CRJ', name: 'CHITTARANJAN', city: 'Paschim Bardhaman', state: 'West Bengal', zone: 'ER', isPopular: false },
  { code: 'DHN', name: 'DHANBAD JN', city: 'Dhanbad', state: 'Jharkhand', zone: 'ECR', isPopular: true },
  { code: 'GMO', name: 'NSC BOSE J GOMOH', city: 'Dhanbad', state: 'Jharkhand', zone: 'ECR', isPopular: false },
  { code: 'BKSC', name: 'BOKARO STEEL CITY', city: 'Bokaro', state: 'Jharkhand', zone: 'SER', isPopular: true },
  { code: 'RNC', name: 'RANCHI JN', city: 'Ranchi', state: 'Jharkhand', zone: 'SER', isPopular: true },
  { code: 'HTE', name: 'HATIA', city: 'Ranchi', state: 'Jharkhand', zone: 'SER', isPopular: false },
  { code: 'MURI', name: 'MURI JN', city: 'Ranchi', state: 'Jharkhand', zone: 'SER', isPopular: false },
  { code: 'TATA', name: 'TATANAGAR JN (JAMSHEDPUR)', city: 'Jamshedpur', state: 'Jharkhand', zone: 'SER', isPopular: true },
  { code: 'CKP', name: 'CHAKRADHARPUR', city: 'West Singhbhum', state: 'Jharkhand', zone: 'SER', isPopular: false },
  { code: 'ROU', name: 'ROURKELA JN', city: 'Rourkela', state: 'Odisha', zone: 'SER', isPopular: true },
  { code: 'JSG', name: 'JHARSUGUDA JN', city: 'Jharsuguda', state: 'Odisha', zone: 'SECR', isPopular: true },
  { code: 'SBP', name: 'SAMBALPUR JN', city: 'Sambalpur', state: 'Odisha', zone: 'ECoR', isPopular: false },
  { code: 'BBS', name: 'BHUBANESWAR', city: 'Bhubaneswar', state: 'Odisha', zone: 'ECoR', isPopular: true },
  { code: 'CTC', name: 'CUTTACK JN', city: 'Cuttack', state: 'Odisha', zone: 'ECoR', isPopular: true },
  { code: 'PURI', name: 'PURI', city: 'Puri', state: 'Odisha', zone: 'ECoR', isPopular: true },
  { code: 'KUR', name: 'KHURDA ROAD JN', city: 'Khurda', state: 'Odisha', zone: 'ECoR', isPopular: true },
  { code: 'BAM', name: 'BRAHMAPUR', city: 'Berhampur', state: 'Odisha', zone: 'ECoR', isPopular: false },
  { code: 'BHC', name: 'BHADRAK', city: 'Bhadrak', state: 'Odisha', zone: 'ECoR', isPopular: false },
  { code: 'BLS', name: 'BALESHWAR (BALASORE)', city: 'Balasore', state: 'Odisha', zone: 'SER', isPopular: false },

  // ─── WEST BENGAL & NORTHEAST (ER, SER, NFR) ─────────────────
  { code: 'HWH', name: 'HOWRAH JN', city: 'Kolkata', state: 'West Bengal', zone: 'ER', isPopular: true },
  { code: 'SDAH', name: 'SEALDAH', city: 'Kolkata', state: 'West Bengal', zone: 'ER', isPopular: true },
  { code: 'KOAA', name: 'KOLKATA (CHITPUR)', city: 'Kolkata', state: 'West Bengal', zone: 'ER', isPopular: true },
  { code: 'SHM', name: 'SHALIMAR', city: 'Howrah', state: 'West Bengal', zone: 'SER', isPopular: true },
  { code: 'SRC', name: 'SANTRAGACHI JN', city: 'Howrah', state: 'West Bengal', zone: 'SER', isPopular: false },
  { code: 'KGP', name: 'KHARAGPUR JN', city: 'Kharagpur', state: 'West Bengal', zone: 'SER', isPopular: true },
  { code: 'BWN', name: 'BARDDHAMAN JN', city: 'Bardhaman', state: 'West Bengal', zone: 'ER', isPopular: true },
  { code: 'DGR', name: 'DURGAPUR', city: 'Durgapur', state: 'West Bengal', zone: 'ER', isPopular: true },
  { code: 'ASN', name: 'ASANSOL JN', city: 'Asansol', state: 'West Bengal', zone: 'ER', isPopular: true },
  { code: 'RPH', name: 'RAMPURHAT JN', city: 'Birbhum', state: 'West Bengal', zone: 'ER', isPopular: false },
  { code: 'BHP', name: 'BOLPUR SHANTINIKETAN', city: 'Birbhum', state: 'West Bengal', zone: 'ER', isPopular: true },
  { code: 'MLDT', name: 'MALDA TOWN', city: 'Malda', state: 'West Bengal', zone: 'ER', isPopular: true },
  { code: 'NFK', name: 'NEW FARAKKA JN', city: 'Murshidabad', state: 'West Bengal', zone: 'ER', isPopular: false },
  { code: 'NJP', name: 'NEW JALPAIGURI (SILIGURI)', city: 'Siliguri', state: 'West Bengal', zone: 'NFR', isPopular: true },
  { code: 'SGUJ', name: 'SILIGURI JN', city: 'Siliguri', state: 'West Bengal', zone: 'NFR', isPopular: false },
  { code: 'APDJ', name: 'ALIPUR DUAR JN', city: 'Alipurduar', state: 'West Bengal', zone: 'NFR', isPopular: false },
  { code: 'NOQ', name: 'NEW ALIPURDUAR', city: 'Alipurduar', state: 'West Bengal', zone: 'NFR', isPopular: false },
  { code: 'NCB', name: 'NEW COOCH BEHAR', city: 'Cooch Behar', state: 'West Bengal', zone: 'NFR', isPopular: false },
  { code: 'NBQ', name: 'NEW BONGAIGAON JN', city: 'Bongaigaon', state: 'Assam', zone: 'NFR', isPopular: true },
  { code: 'GHY', name: 'GUWAHATI', city: 'Guwahati', state: 'Assam', zone: 'NFR', isPopular: true },
  { code: 'KYQ', name: 'KAMAKHYA JN', city: 'Guwahati', state: 'Assam', zone: 'NFR', isPopular: true },
  { code: 'LMG', name: 'LUMDING JN', city: 'Hojai', state: 'Assam', zone: 'NFR', isPopular: false },
  { code: 'DBRG', name: 'DIBRUGARH', city: 'Dibrugarh', state: 'Assam', zone: 'NFR', isPopular: true },
  { code: 'TSK', name: 'TINSUKIA JN', city: 'Tinsukia', state: 'Assam', zone: 'NFR', isPopular: false },
  { code: 'NTSK', name: 'NEW TINSUKIA JN', city: 'Tinsukia', state: 'Assam', zone: 'NFR', isPopular: false },
  { code: 'DMV', name: 'DIMAPUR', city: 'Dimapur', state: 'Nagaland', zone: 'NFR', isPopular: true },
  { code: 'AGTL', name: 'AGARTALA', city: 'Agartala', state: 'Tripura', zone: 'NFR', isPopular: true },
  { code: 'SCL', name: 'SILCHAR', city: 'Cachar', state: 'Assam', zone: 'NFR', isPopular: false },

  // ─── SOUTH ZONE (SR, SCR, SWR) ──────────────────────────────
  { code: 'MAS', name: 'CHENNAI CENTRAL (MGR CHENNAI)', city: 'Chennai', state: 'Tamil Nadu', zone: 'SR', isPopular: true },
  { code: 'MS', name: 'CHENNAI EGMORE', city: 'Chennai', state: 'Tamil Nadu', zone: 'SR', isPopular: true },
  { code: 'TBM', name: 'TAMBARAM', city: 'Chennai', state: 'Tamil Nadu', zone: 'SR', isPopular: true },
  { code: 'AJJ', name: 'ARAKKONAM JN', city: 'Arakkonam', state: 'Tamil Nadu', zone: 'SR', isPopular: false },
  { code: 'KPD', name: 'KATPADI JN (VELLORE)', city: 'Vellore', state: 'Tamil Nadu', zone: 'SR', isPopular: true },
  { code: 'JTJ', name: 'JOLARPETTAI JN', city: 'Tirupattur', state: 'Tamil Nadu', zone: 'SR', isPopular: false },
  { code: 'SA', name: 'SALEM JN', city: 'Salem', state: 'Tamil Nadu', zone: 'SR', isPopular: true },
  { code: 'ED', name: 'ERODE JN', city: 'Erode', state: 'Tamil Nadu', zone: 'SR', isPopular: true },
  { code: 'TUP', name: 'TIRUPPUR', city: 'Tiruppur', state: 'Tamil Nadu', zone: 'SR', isPopular: false },
  { code: 'CBE', name: 'COIMBATORE JN', city: 'Coimbatore', state: 'Tamil Nadu', zone: 'SR', isPopular: true },
  { code: 'TPJ', name: 'TIRUCHCHIRAPPALLI JN (TRICHY)', city: 'Tiruchirappalli', state: 'Tamil Nadu', zone: 'SR', isPopular: true },
  { code: 'MDU', name: 'MADURAI JN', city: 'Madurai', state: 'Tamil Nadu', zone: 'SR', isPopular: true },
  { code: 'DG', name: 'DINDIGUL JN', city: 'Dindigul', state: 'Tamil Nadu', zone: 'SR', isPopular: false },
  { code: 'TEN', name: 'TIRUNELVELI JN', city: 'Tirunelveli', state: 'Tamil Nadu', zone: 'SR', isPopular: true },
  { code: 'CAPE', name: 'KANYAKUMARI', city: 'Kanyakumari', state: 'Tamil Nadu', zone: 'SR', isPopular: true },
  { code: 'NCJ', name: 'NAGERCOIL JN', city: 'Nagercoil', state: 'Tamil Nadu', zone: 'SR', isPopular: true },
  { code: 'RMM', name: 'RAMESWARAM', city: 'Rameswaram', state: 'Tamil Nadu', zone: 'SR', isPopular: true },
  { code: 'MV', name: 'MAYILADUTURAI JN', city: 'Mayiladuthurai', state: 'Tamil Nadu', zone: 'SR', isPopular: false },
  { code: 'TVR', name: 'THIRUVARUR JN', city: 'Thiruvarur', state: 'Tamil Nadu', zone: 'SR', isPopular: false },
  { code: 'TJ', name: 'THANJAVUR JN', city: 'Thanjavur', state: 'Tamil Nadu', zone: 'SR', isPopular: false },
  { code: 'VM', name: 'VILLUPURAM JN', city: 'Villupuram', state: 'Tamil Nadu', zone: 'SR', isPopular: true },
  { code: 'CUD', name: 'TIRUPADRIPULYUR (CUDDALORE)', city: 'Cuddalore', state: 'Tamil Nadu', zone: 'SR', isPopular: false },
  { code: 'PDY', name: 'PUDUCHERRY', city: 'Puducherry', state: 'Puducherry', zone: 'SR', isPopular: true },

  // ─── KERALA (SR) ────────────────────────────────────────────
  { code: 'TVC', name: 'THIRUVANANTHAPURAM CENTRAL', city: 'Thiruvananthapuram', state: 'Kerala', zone: 'SR', isPopular: true },
  { code: 'KCVL', name: 'KOCHUVELI', city: 'Thiruvananthapuram', state: 'Kerala', zone: 'SR', isPopular: true },
  { code: 'QLN', name: 'KOLLAM JN (QUILON)', city: 'Kollam', state: 'Kerala', zone: 'SR', isPopular: true },
  { code: 'KYJ', name: 'KAYANKULAM JN', city: 'Alappuzha', state: 'Kerala', zone: 'SR', isPopular: false },
  { code: 'ALLP', name: 'ALAPPUZHA (ALLEPPEY)', city: 'Alappuzha', state: 'Kerala', zone: 'SR', isPopular: true },
  { code: 'CNGR', name: 'CHENGANNUR (SABARIMALA)', city: 'Alappuzha', state: 'Kerala', zone: 'SR', isPopular: true },
  { code: 'TRVL', name: 'TIRUVALLA', city: 'Pathanamthitta', state: 'Kerala', zone: 'SR', isPopular: false },
  { code: 'KTYM', name: 'KOTTAYAM', city: 'Kottayam', state: 'Kerala', zone: 'SR', isPopular: true },
  { code: 'ERN', name: 'ERNAKULAM TOWN (NORTH)', city: 'Kochi', state: 'Kerala', zone: 'SR', isPopular: true },
  { code: 'ERS', name: 'ERNAKULAM JN (SOUTH)', city: 'Kochi', state: 'Kerala', zone: 'SR', isPopular: true },
  { code: 'AWY', name: 'ALUVA (ALWAYE)', city: 'Kochi', state: 'Kerala', zone: 'SR', isPopular: false },
  { code: 'TCR', name: 'THRISUR', city: 'Thrissur', state: 'Kerala', zone: 'SR', isPopular: true },
  { code: 'SRR', name: 'SHORANUR JN', city: 'Palakkad', state: 'Kerala', zone: 'SR', isPopular: true },
  { code: 'PGT', name: 'PALAKKAD JN (PALGHAT)', city: 'Palakkad', state: 'Kerala', zone: 'SR', isPopular: true },
  { code: 'TIR', name: 'TIRUR', city: 'Malappuram', state: 'Kerala', zone: 'SR', isPopular: false },
  { code: 'CLT', name: 'KOZHIKODE (CALICUT)', city: 'Kozhikode', state: 'Kerala', zone: 'SR', isPopular: true },
  { code: 'BDJ', name: 'VADAKARA', city: 'Kozhikode', state: 'Kerala', zone: 'SR', isPopular: false },
  { code: 'TLY', name: 'THALASSERY', city: 'Kannur', state: 'Kerala', zone: 'SR', isPopular: false },
  { code: 'CAN', name: 'KANNUR (CANNANORE)', city: 'Kannur', state: 'Kerala', zone: 'SR', isPopular: true },
  { code: 'KGQ', name: 'KASARAGOD', city: 'Kasaragod', state: 'Kerala', zone: 'SR', isPopular: false },
  { code: 'MAQ', name: 'MANGALURU CENTRAL', city: 'Mangaluru', state: 'Karnataka', zone: 'SR', isPopular: true },
  { code: 'MAJN', name: 'MANGALURU JN', city: 'Mangaluru', state: 'Karnataka', zone: 'SR', isPopular: true },

  // ─── KARNATAKA (SWR) ────────────────────────────────────────
  { code: 'SBC', name: 'KSR BENGALURU (BANGALORE CITY)', city: 'Bengaluru', state: 'Karnataka', zone: 'SWR', isPopular: true },
  { code: 'YPR', name: 'YESVANTPUR JN', city: 'Bengaluru', state: 'Karnataka', zone: 'SWR', isPopular: true },
  { code: 'SMVB', name: 'SMVT BENGALURU (SIR M VISVESVARAYA TERMINAL)', city: 'Bengaluru', state: 'Karnataka', zone: 'SWR', isPopular: true },
  { code: 'BNC', name: 'BENGALURU CANTT', city: 'Bengaluru', state: 'Karnataka', zone: 'SWR', isPopular: false },
  { code: 'KJM', name: 'KRISHNARAJAPURAM', city: 'Bengaluru', state: 'Karnataka', zone: 'SWR', isPopular: false },
  { code: 'WFD', name: 'WHITEFIELD', city: 'Bengaluru', state: 'Karnataka', zone: 'SWR', isPopular: false },
  { code: 'BWT', name: 'BANGARAPET JN', city: 'Kolar', state: 'Karnataka', zone: 'SWR', isPopular: false },
  { code: 'MYS', name: 'MYSURU JN (MYSORE)', city: 'Mysuru', state: 'Karnataka', zone: 'SWR', isPopular: true },
  { code: 'HAS', name: 'HASSAN JN', city: 'Hassan', state: 'Karnataka', zone: 'SWR', isPopular: false },
  { code: 'TK', name: 'TUMAKURU (TUMKUR)', city: 'Tumakuru', state: 'Karnataka', zone: 'SWR', isPopular: false },
  { code: 'ASK', name: 'ARSIKERE JN', city: 'Hassan', state: 'Karnataka', zone: 'SWR', isPopular: false },
  { code: 'DVG', name: 'DAVANGERE', city: 'Davanagere', state: 'Karnataka', zone: 'SWR', isPopular: false },
  { code: 'UBL', name: 'SSS HUBBALLI JN (HUBLI)', city: 'Hubballi', state: 'Karnataka', zone: 'SWR', isPopular: true },
  { code: 'DWR', name: 'DHARWAD', city: 'Dharwad', state: 'Karnataka', zone: 'SWR', isPopular: false },
  { code: 'BGM', name: 'BELAGAVI (BELGAUM)', city: 'Belagavi', state: 'Karnataka', zone: 'SWR', isPopular: true },
  { code: 'BJP', name: 'VIJAYAPURA (BIJAPUR)', city: 'Vijayapura', state: 'Karnataka', zone: 'SWR', isPopular: false },
  { code: 'BGK', name: 'BAGALKOT', city: 'Bagalkot', state: 'Karnataka', zone: 'SWR', isPopular: false },
  { code: 'GDG', name: 'GADAG JN', city: 'Gadag', state: 'Karnataka', zone: 'SWR', isPopular: false },
  { code: 'KBL', name: 'KOPPAL', city: 'Koppal', state: 'Karnataka', zone: 'SWR', isPopular: false },
  { code: 'HPT', name: 'HOSAPETE JN (HAMPI)', city: 'Ballari', state: 'Karnataka', zone: 'SWR', isPopular: true },
  { code: 'BAY', name: 'BALLARI JN (BELLARY)', city: 'Ballari', state: 'Karnataka', zone: 'SWR', isPopular: false },
  { code: 'RC', name: 'RAICHUR JN', city: 'Raichur', state: 'Karnataka', zone: 'SCR', isPopular: false },
  { code: 'YG', name: 'YADGIR', city: 'Yadgir', state: 'Karnataka', zone: 'SCR', isPopular: false },
  { code: 'WADI', name: 'WADI JN', city: 'Kalaburagi', state: 'Karnataka', zone: 'CR', isPopular: true },
  { code: 'KLBG', name: 'KALABURAGI (GULBARGA)', city: 'Kalaburagi', state: 'Karnataka', zone: 'CR', isPopular: true },
  { code: 'BIDR', name: 'BIDAR', city: 'Bidar', state: 'Karnataka', zone: 'SCR', isPopular: false },

  // ─── TELANGANA & ANDHRA PRADESH (SCR, ECoR) ─────────────────
  { code: 'SC', name: 'SECUNDERABAD JN', city: 'Hyderabad', state: 'Telangana', zone: 'SCR', isPopular: true },
  { code: 'HYB', name: 'HYDERABAD DECCAN (NAM PALLY)', city: 'Hyderabad', state: 'Telangana', zone: 'SCR', isPopular: true },
  { code: 'KCG', name: 'KACHEGUDA', city: 'Hyderabad', state: 'Telangana', zone: 'SCR', isPopular: true },
  { code: 'LPI', name: 'LINGAMPALLI', city: 'Hyderabad', state: 'Telangana', zone: 'SCR', isPopular: false },
  { code: 'CHZ', name: 'CHARLAPALLI', city: 'Hyderabad', state: 'Telangana', zone: 'SCR', isPopular: false },
  { code: 'KZJ', name: 'KAZIPET JN', city: 'Warangal', state: 'Telangana', zone: 'SCR', isPopular: true },
  { code: 'WL', name: 'WARANGAL', city: 'Warangal', state: 'Telangana', zone: 'SCR', isPopular: true },
  { code: 'KMT', name: 'KHAMMAM', city: 'Khammam', state: 'Telangana', zone: 'SCR', isPopular: false },
  { code: 'MCI', name: 'MANCHIRYAL', city: 'Mancherial', state: 'Telangana', zone: 'SCR', isPopular: false },
  { code: 'RDM', name: 'RAMAGUNDAM', city: 'Peddapalli', state: 'Telangana', zone: 'SCR', isPopular: false },
  { code: 'NZB', name: 'NIZAMABAD JN', city: 'Nizamabad', state: 'Telangana', zone: 'SCR', isPopular: false },
  { code: 'MBNR', name: 'MAHBUBNAGAR', city: 'Mahabubnagar', state: 'Telangana', zone: 'SCR', isPopular: false },
  { code: 'BZA', name: 'VIJAYAWADA JN', city: 'Vijayawada', state: 'Andhra Pradesh', zone: 'SCR', isPopular: true },
  { code: 'GNT', name: 'GUNTUR JN', city: 'Guntur', state: 'Andhra Pradesh', zone: 'SCR', isPopular: true },
  { code: 'TEL', name: 'TENALI JN', city: 'Tenali', state: 'Andhra Pradesh', zone: 'SCR', isPopular: false },
  { code: 'OGL', name: 'ONGOLE', city: 'Ongole', state: 'Andhra Pradesh', zone: 'SCR', isPopular: false },
  { code: 'NLR', name: 'NELLORE', city: 'Nellore', state: 'Andhra Pradesh', zone: 'SCR', isPopular: true },
  { code: 'GDR', name: 'GUDUR JN', city: 'Nellore', state: 'Andhra Pradesh', zone: 'SCR', isPopular: false },
  { code: 'RU', name: 'RENIGUNTA JN', city: 'Tirupati', state: 'Andhra Pradesh', zone: 'SCR', isPopular: true },
  { code: 'TPTY', name: 'TIRUPATI MAIN', city: 'Tirupati', state: 'Andhra Pradesh', zone: 'SCR', isPopular: true },
  { code: 'KDP', name: 'KADAPA (CUDDAPAH)', city: 'Kadapa', state: 'Andhra Pradesh', zone: 'SCR', isPopular: false },
  { code: 'YA', name: 'YERRAGUNTLA JN', city: 'Kadapa', state: 'Andhra Pradesh', zone: 'SCR', isPopular: false },
  { code: 'DHNE', name: 'DHONE JN', city: 'Nandyal', state: 'Andhra Pradesh', zone: 'SCR', isPopular: false },
  { code: 'KRNT', name: 'KURNOOL CITY', city: 'Kurnool', state: 'Andhra Pradesh', zone: 'SCR', isPopular: true },
  { code: 'GTL', name: 'GUNTAKAL JN', city: 'Anantapur', state: 'Andhra Pradesh', zone: 'SCR', isPopular: true },
  { code: 'ATP', name: 'ANANTAPUR', city: 'Anantapur', state: 'Andhra Pradesh', zone: 'SCR', isPopular: false },
  { code: 'EE', name: 'ELURU', city: 'Eluru', state: 'Andhra Pradesh', zone: 'SCR', isPopular: false },
  { code: 'TDD', name: 'TADEPALLIGUDEM', city: 'West Godavari', state: 'Andhra Pradesh', zone: 'SCR', isPopular: false },
  { code: 'RJY', name: 'RAJAHMUNDRY', city: 'Rajahmundry', state: 'Andhra Pradesh', zone: 'SCR', isPopular: true },
  { code: 'SLO', name: 'SAMALKOT JN (KAKINADA)', city: 'Kakinada', state: 'Andhra Pradesh', zone: 'SCR', isPopular: false },
  { code: 'CCT', name: 'KAKINADA TOWN', city: 'Kakinada', state: 'Andhra Pradesh', zone: 'SCR', isPopular: false },
  { code: 'COA', name: 'KAKINADA PORT', city: 'Kakinada', state: 'Andhra Pradesh', zone: 'SCR', isPopular: false },
  { code: 'ANV', name: 'ANNAVARAM', city: 'Kakinada', state: 'Andhra Pradesh', zone: 'SCR', isPopular: false },
  { code: 'TUNI', name: 'TUNI', city: 'Kakinada', state: 'Andhra Pradesh', zone: 'SCR', isPopular: false },
  { code: 'AKP', name: 'ANAKAPALLE', city: 'Visakhapatnam', state: 'Andhra Pradesh', zone: 'SCR', isPopular: false },
  { code: 'DVD', name: 'DUVVADA', city: 'Visakhapatnam', state: 'Andhra Pradesh', zone: 'ECoR', isPopular: false },
  { code: 'VSKP', name: 'VISAKHAPATNAM JN', city: 'Visakhapatnam', state: 'Andhra Pradesh', zone: 'ECoR', isPopular: true },
  { code: 'VZM', name: 'VIZIANAGARAM JN', city: 'Vizianagaram', state: 'Andhra Pradesh', zone: 'ECoR', isPopular: false },
  { code: 'CHE', name: 'SRIKAKULAM ROAD', city: 'Srikakulam', state: 'Andhra Pradesh', zone: 'ECoR', isPopular: false },
];

